using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.IO;
using System.Drawing;
using NativeExcel;

public partial class rpt_60300010_monthly_revenue_usd_lotus : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

        ESysLib.SetUser("crm");
        string l_date = Request["p_month"];

        string str_month = l_date.Substring(4, 2) + "/" + l_date.Substring(0, 4);

        string TemplateFile = "rpt_60300010_monthly_revenue_usd_lotus.xls";
        string TempFile = "../../../system/temp/rpt_60300010_monthly_revenue_usd_lotus_" + Session["User_ID"].ToString() + ".xls";
        TemplateFile = Server.MapPath(TemplateFile);
        TempFile = Server.MapPath(TempFile);

        //Create a new workbook
        IWorkbook exBook = NativeExcel.Factory.OpenWorkbook(TemplateFile);

        //Add worksheet
        IWorksheet exSheet = exBook.Worksheets[1];

        IRange range;

        //bind data to excel file
        string para = "";
        DataTable dt;

        para = "'" + l_date + "'";
        dt = ESysLib.TableReadOpenCursor("crm.sp_sel_revenue_monthly_vnd", para);
        //-----header---  
        exSheet.Cells[3, 2].Value = str_month;
        //exSheet.Cells[3, 33].Value = strPrintDate; 
        exSheet.Cells[3, 33].Value = dt.Rows[0]["print_time"].ToString();
        //--set-----DataBind--in---Master---


        exSheet.Cells[6, 3].Value = double.Parse(dt.Rows[0]["mm_sum"].ToString());
        exSheet.Cells[6, 4].Value = double.Parse(dt.Rows[0]["avg_month_amt"].ToString());
        exSheet.Cells[6, 5].Value  = double.Parse(dt.Rows[0]["d1"].ToString());
        exSheet.Cells[6, 6].Value  = double.Parse(dt.Rows[0]["d2"].ToString());
        exSheet.Cells[6, 7].Value  = double.Parse(dt.Rows[0]["d3"].ToString());
        exSheet.Cells[6, 8].Value  = double.Parse(dt.Rows[0]["d4"].ToString());
        exSheet.Cells[6, 9].Value  = double.Parse(dt.Rows[0]["d5"].ToString());
        exSheet.Cells[6, 10].Value  = double.Parse(dt.Rows[0]["d6"].ToString());
        exSheet.Cells[6, 11].Value = double.Parse(dt.Rows[0]["d7"].ToString());
        exSheet.Cells[6, 12].Value = double.Parse(dt.Rows[0]["d8"].ToString());
        exSheet.Cells[6, 13].Value = double.Parse(dt.Rows[0]["d9"].ToString());
        exSheet.Cells[6, 14].Value = double.Parse(dt.Rows[0]["d10"].ToString());
        exSheet.Cells[6, 15].Value = double.Parse(dt.Rows[0]["d11"].ToString());
        exSheet.Cells[6, 16].Value = double.Parse(dt.Rows[0]["d12"].ToString());
        exSheet.Cells[6, 17].Value = double.Parse(dt.Rows[0]["d13"].ToString());
        exSheet.Cells[6, 18].Value = double.Parse(dt.Rows[0]["d14"].ToString());
        exSheet.Cells[6, 19].Value = double.Parse(dt.Rows[0]["d15"].ToString());
        exSheet.Cells[6, 20].Value = double.Parse(dt.Rows[0]["d16"].ToString());
        exSheet.Cells[6, 21].Value = double.Parse(dt.Rows[0]["d17"].ToString());
        exSheet.Cells[6, 22].Value  = double.Parse(dt.Rows[0]["d18"].ToString());
        exSheet.Cells[6, 23].Value  = double.Parse(dt.Rows[0]["d19"].ToString());
        exSheet.Cells[6, 24].Value  = double.Parse(dt.Rows[0]["d20"].ToString());
        exSheet.Cells[6, 25].Value  = double.Parse(dt.Rows[0]["d21"].ToString());
        exSheet.Cells[6, 26].Value  = double.Parse(dt.Rows[0]["d22"].ToString());
        exSheet.Cells[6, 27].Value  = double.Parse(dt.Rows[0]["d23"].ToString());
        exSheet.Cells[6, 28].Value = double.Parse(dt.Rows[0]["d24"].ToString());
        exSheet.Cells[6, 29].Value = double.Parse(dt.Rows[0]["d25"].ToString());
        exSheet.Cells[6, 30].Value = double.Parse(dt.Rows[0]["d26"].ToString());
        exSheet.Cells[6, 31].Value = double.Parse(dt.Rows[0]["d27"].ToString());
        exSheet.Cells[6, 32].Value = double.Parse(dt.Rows[0]["d28"].ToString());
        exSheet.Cells[6, 33].Value = double.Parse(dt.Rows[0]["d29"].ToString());
        exSheet.Cells[6, 34].Value = double.Parse(dt.Rows[0]["d30"].ToString());
        exSheet.Cells[6, 35].Value = double.Parse(dt.Rows[0]["d31"].ToString());


        exSheet.Cells[7, 3].Value = double.Parse(dt.Rows[1]["mm_sum"].ToString());
        exSheet.Cells[7, 4].Value = double.Parse(dt.Rows[1]["avg_month_amt"].ToString());
        exSheet.Cells[7, 5].Value = double.Parse(dt.Rows[1]["d1"].ToString());
        exSheet.Cells[7, 6].Value = double.Parse(dt.Rows[1]["d2"].ToString());
        exSheet.Cells[7, 7].Value = double.Parse(dt.Rows[1]["d3"].ToString());
        exSheet.Cells[7, 8].Value = double.Parse(dt.Rows[1]["d4"].ToString());
        exSheet.Cells[7, 9].Value = double.Parse(dt.Rows[1]["d5"].ToString());
        exSheet.Cells[7, 10].Value = double.Parse(dt.Rows[1]["d6"].ToString());
        exSheet.Cells[7, 11].Value = double.Parse(dt.Rows[1]["d7"].ToString());
        exSheet.Cells[7, 12].Value = double.Parse(dt.Rows[1]["d8"].ToString());
        exSheet.Cells[7, 13].Value = double.Parse(dt.Rows[1]["d9"].ToString());
        exSheet.Cells[7, 14].Value = double.Parse(dt.Rows[1]["d10"].ToString());
        exSheet.Cells[7, 15].Value = double.Parse(dt.Rows[1]["d11"].ToString());
        exSheet.Cells[7, 16].Value = double.Parse(dt.Rows[1]["d12"].ToString());
        exSheet.Cells[7, 17].Value = double.Parse(dt.Rows[1]["d13"].ToString());
        exSheet.Cells[7, 18].Value = double.Parse(dt.Rows[1]["d14"].ToString());
        exSheet.Cells[7, 19].Value = double.Parse(dt.Rows[1]["d15"].ToString());
        exSheet.Cells[7, 20].Value = double.Parse(dt.Rows[1]["d16"].ToString());
        exSheet.Cells[7, 21].Value = double.Parse(dt.Rows[1]["d17"].ToString());
        exSheet.Cells[7, 22].Value = double.Parse(dt.Rows[1]["d18"].ToString());
        exSheet.Cells[7, 23].Value = double.Parse(dt.Rows[1]["d19"].ToString());
        exSheet.Cells[7, 24].Value = double.Parse(dt.Rows[1]["d20"].ToString());
        exSheet.Cells[7, 25].Value = double.Parse(dt.Rows[1]["d21"].ToString());
        exSheet.Cells[7, 26].Value = double.Parse(dt.Rows[1]["d22"].ToString());
        exSheet.Cells[7, 27].Value = double.Parse(dt.Rows[1]["d23"].ToString());
        exSheet.Cells[7, 28].Value = double.Parse(dt.Rows[1]["d24"].ToString());
        exSheet.Cells[7, 29].Value = double.Parse(dt.Rows[1]["d25"].ToString());
        exSheet.Cells[7, 30].Value = double.Parse(dt.Rows[1]["d26"].ToString());
        exSheet.Cells[7, 31].Value = double.Parse(dt.Rows[1]["d27"].ToString());
        exSheet.Cells[7, 32].Value = double.Parse(dt.Rows[1]["d28"].ToString());
        exSheet.Cells[7, 33].Value = double.Parse(dt.Rows[1]["d29"].ToString());
        exSheet.Cells[7, 34].Value = double.Parse(dt.Rows[1]["d30"].ToString());
        exSheet.Cells[7, 35].Value = double.Parse(dt.Rows[1]["d31"].ToString());

        exSheet.Cells[8, 3].Value = double.Parse(dt.Rows[2]["mm_sum"].ToString());
        exSheet.Cells[8, 4].Value = double.Parse(dt.Rows[2]["avg_month_amt"].ToString());
        exSheet.Cells[8, 5].Value = double.Parse(dt.Rows[2]["d1"].ToString());
        exSheet.Cells[8, 6].Value = double.Parse(dt.Rows[2]["d2"].ToString());
        exSheet.Cells[8, 7].Value = double.Parse(dt.Rows[2]["d3"].ToString());
        exSheet.Cells[8, 8].Value = double.Parse(dt.Rows[2]["d4"].ToString());
        exSheet.Cells[8, 9].Value = double.Parse(dt.Rows[2]["d5"].ToString());
        exSheet.Cells[8, 10].Value = double.Parse(dt.Rows[2]["d6"].ToString());
        exSheet.Cells[8, 11].Value = double.Parse(dt.Rows[2]["d7"].ToString());
        exSheet.Cells[8, 12].Value = double.Parse(dt.Rows[2]["d8"].ToString());
        exSheet.Cells[8, 13].Value = double.Parse(dt.Rows[2]["d9"].ToString());
        exSheet.Cells[8, 14].Value = double.Parse(dt.Rows[2]["d10"].ToString());
        exSheet.Cells[8, 15].Value = double.Parse(dt.Rows[2]["d11"].ToString());
        exSheet.Cells[8, 16].Value = double.Parse(dt.Rows[2]["d12"].ToString());
        exSheet.Cells[8, 17].Value = double.Parse(dt.Rows[2]["d13"].ToString());
        exSheet.Cells[8, 18].Value = double.Parse(dt.Rows[2]["d14"].ToString());
        exSheet.Cells[8, 19].Value = double.Parse(dt.Rows[2]["d15"].ToString());
        exSheet.Cells[8, 20].Value = double.Parse(dt.Rows[2]["d16"].ToString());
        exSheet.Cells[8, 21].Value = double.Parse(dt.Rows[2]["d17"].ToString());
        exSheet.Cells[8, 22].Value = double.Parse(dt.Rows[2]["d18"].ToString());
        exSheet.Cells[8, 23].Value = double.Parse(dt.Rows[2]["d19"].ToString());
        exSheet.Cells[8, 24].Value = double.Parse(dt.Rows[2]["d20"].ToString());
        exSheet.Cells[8, 25].Value = double.Parse(dt.Rows[2]["d21"].ToString());
        exSheet.Cells[8, 26].Value = double.Parse(dt.Rows[2]["d22"].ToString());
        exSheet.Cells[8, 27].Value = double.Parse(dt.Rows[2]["d23"].ToString());
        exSheet.Cells[8, 28].Value = double.Parse(dt.Rows[2]["d24"].ToString());
        exSheet.Cells[8, 29].Value = double.Parse(dt.Rows[2]["d25"].ToString());
        exSheet.Cells[8, 30].Value = double.Parse(dt.Rows[2]["d26"].ToString());
        exSheet.Cells[8, 31].Value = double.Parse(dt.Rows[2]["d27"].ToString());
        exSheet.Cells[8, 32].Value = double.Parse(dt.Rows[2]["d28"].ToString());
        exSheet.Cells[8, 33].Value = double.Parse(dt.Rows[2]["d29"].ToString());
        exSheet.Cells[8, 34].Value = double.Parse(dt.Rows[2]["d30"].ToString());
        exSheet.Cells[8, 35].Value = double.Parse(dt.Rows[2]["d31"].ToString());

        exSheet.Cells[9, 3].Value = double.Parse(dt.Rows[3]["mm_sum"].ToString());
        exSheet.Cells[9, 4].Value = double.Parse(dt.Rows[3]["avg_month_amt"].ToString());
        exSheet.Cells[9, 5].Value = double.Parse(dt.Rows[3]["d1"].ToString());
        exSheet.Cells[9, 6].Value = double.Parse(dt.Rows[3]["d2"].ToString());
        exSheet.Cells[9, 7].Value = double.Parse(dt.Rows[3]["d3"].ToString());
        exSheet.Cells[9, 8].Value = double.Parse(dt.Rows[3]["d4"].ToString());
        exSheet.Cells[9, 9].Value = double.Parse(dt.Rows[3]["d5"].ToString());
        exSheet.Cells[9, 10].Value = double.Parse(dt.Rows[3]["d6"].ToString());
        exSheet.Cells[9, 11].Value = double.Parse(dt.Rows[3]["d7"].ToString());
        exSheet.Cells[9, 12].Value = double.Parse(dt.Rows[3]["d8"].ToString());
        exSheet.Cells[9, 13].Value = double.Parse(dt.Rows[3]["d9"].ToString());
        exSheet.Cells[9, 14].Value = double.Parse(dt.Rows[3]["d10"].ToString());
        exSheet.Cells[9, 15].Value = double.Parse(dt.Rows[3]["d11"].ToString());
        exSheet.Cells[9, 16].Value = double.Parse(dt.Rows[3]["d12"].ToString());
        exSheet.Cells[9, 17].Value = double.Parse(dt.Rows[3]["d13"].ToString());
        exSheet.Cells[9, 18].Value = double.Parse(dt.Rows[3]["d14"].ToString());
        exSheet.Cells[9, 19].Value = double.Parse(dt.Rows[3]["d15"].ToString());
        exSheet.Cells[9, 20].Value = double.Parse(dt.Rows[3]["d16"].ToString());
        exSheet.Cells[9, 21].Value = double.Parse(dt.Rows[3]["d17"].ToString());
        exSheet.Cells[9, 22].Value = double.Parse(dt.Rows[3]["d18"].ToString());
        exSheet.Cells[9, 23].Value = double.Parse(dt.Rows[3]["d19"].ToString());
        exSheet.Cells[9, 24].Value = double.Parse(dt.Rows[3]["d20"].ToString());
        exSheet.Cells[9, 25].Value = double.Parse(dt.Rows[3]["d21"].ToString());
        exSheet.Cells[9, 26].Value = double.Parse(dt.Rows[3]["d22"].ToString());
        exSheet.Cells[9, 27].Value = double.Parse(dt.Rows[3]["d23"].ToString());
        exSheet.Cells[9, 28].Value = double.Parse(dt.Rows[3]["d24"].ToString());
        exSheet.Cells[9, 29].Value = double.Parse(dt.Rows[3]["d25"].ToString());
        exSheet.Cells[9, 30].Value = double.Parse(dt.Rows[3]["d26"].ToString());
        exSheet.Cells[9, 31].Value = double.Parse(dt.Rows[3]["d27"].ToString());
        exSheet.Cells[9, 32].Value = double.Parse(dt.Rows[3]["d28"].ToString());
        exSheet.Cells[9, 33].Value = double.Parse(dt.Rows[3]["d29"].ToString());
        exSheet.Cells[9, 34].Value = double.Parse(dt.Rows[3]["d30"].ToString());
        exSheet.Cells[9, 35].Value = double.Parse(dt.Rows[3]["d31"].ToString());

        exSheet.Cells[10, 3].Value = double.Parse(dt.Rows[4]["mm_sum"].ToString());
        exSheet.Cells[10, 4].Value = double.Parse(dt.Rows[4]["avg_month_amt"].ToString());
        exSheet.Cells[10, 5].Value = double.Parse(dt.Rows[4]["d1"].ToString());
        exSheet.Cells[10, 6].Value = double.Parse(dt.Rows[4]["d2"].ToString());
        exSheet.Cells[10, 7].Value = double.Parse(dt.Rows[4]["d3"].ToString());
        exSheet.Cells[10, 8].Value = double.Parse(dt.Rows[4]["d4"].ToString());
        exSheet.Cells[10, 9].Value = double.Parse(dt.Rows[4]["d5"].ToString());
        exSheet.Cells[10, 10].Value = double.Parse(dt.Rows[4]["d6"].ToString());
        exSheet.Cells[10, 11].Value = double.Parse(dt.Rows[4]["d7"].ToString());
        exSheet.Cells[10, 12].Value = double.Parse(dt.Rows[4]["d8"].ToString());
        exSheet.Cells[10, 13].Value = double.Parse(dt.Rows[4]["d9"].ToString());
        exSheet.Cells[10, 14].Value = double.Parse(dt.Rows[4]["d10"].ToString());
        exSheet.Cells[10, 15].Value = double.Parse(dt.Rows[4]["d11"].ToString());
        exSheet.Cells[10, 16].Value = double.Parse(dt.Rows[4]["d12"].ToString());
        exSheet.Cells[10, 17].Value = double.Parse(dt.Rows[4]["d13"].ToString());
        exSheet.Cells[10, 18].Value = double.Parse(dt.Rows[4]["d14"].ToString());
        exSheet.Cells[10, 19].Value = double.Parse(dt.Rows[4]["d15"].ToString());
        exSheet.Cells[10, 20].Value = double.Parse(dt.Rows[4]["d16"].ToString());
        exSheet.Cells[10, 21].Value = double.Parse(dt.Rows[4]["d17"].ToString());
        exSheet.Cells[10, 22].Value = double.Parse(dt.Rows[4]["d18"].ToString());
        exSheet.Cells[10, 23].Value = double.Parse(dt.Rows[4]["d19"].ToString());
        exSheet.Cells[10, 24].Value = double.Parse(dt.Rows[4]["d20"].ToString());
        exSheet.Cells[10, 25].Value = double.Parse(dt.Rows[4]["d21"].ToString());
        exSheet.Cells[10, 26].Value = double.Parse(dt.Rows[4]["d22"].ToString());
        exSheet.Cells[10, 27].Value = double.Parse(dt.Rows[4]["d23"].ToString());
        exSheet.Cells[10, 28].Value = double.Parse(dt.Rows[4]["d24"].ToString());
        exSheet.Cells[10, 29].Value = double.Parse(dt.Rows[4]["d25"].ToString());
        exSheet.Cells[10, 30].Value = double.Parse(dt.Rows[4]["d26"].ToString());
        exSheet.Cells[10, 31].Value = double.Parse(dt.Rows[4]["d27"].ToString());
        exSheet.Cells[10, 32].Value = double.Parse(dt.Rows[4]["d28"].ToString());
        exSheet.Cells[10, 33].Value = double.Parse(dt.Rows[4]["d29"].ToString());
        exSheet.Cells[10, 34].Value = double.Parse(dt.Rows[4]["d30"].ToString());
        exSheet.Cells[10, 35].Value = double.Parse(dt.Rows[4]["d31"].ToString());

        exSheet.Cells[11, 3].Value = double.Parse(dt.Rows[5]["mm_sum"].ToString());
        exSheet.Cells[11, 4].Value = double.Parse(dt.Rows[5]["avg_month_amt"].ToString());
        exSheet.Cells[11, 5].Value = double.Parse(dt.Rows[5]["d1"].ToString());
        exSheet.Cells[11, 6].Value = double.Parse(dt.Rows[5]["d2"].ToString());
        exSheet.Cells[11, 7].Value = double.Parse(dt.Rows[5]["d3"].ToString());
        exSheet.Cells[11, 8].Value = double.Parse(dt.Rows[5]["d4"].ToString());
        exSheet.Cells[11, 9].Value = double.Parse(dt.Rows[5]["d5"].ToString());
        exSheet.Cells[11, 10].Value = double.Parse(dt.Rows[5]["d6"].ToString());
        exSheet.Cells[11, 11].Value = double.Parse(dt.Rows[5]["d7"].ToString());
        exSheet.Cells[11, 12].Value = double.Parse(dt.Rows[5]["d8"].ToString());
        exSheet.Cells[11, 13].Value = double.Parse(dt.Rows[5]["d9"].ToString());
        exSheet.Cells[11, 14].Value = double.Parse(dt.Rows[5]["d10"].ToString());
        exSheet.Cells[11, 15].Value = double.Parse(dt.Rows[5]["d11"].ToString());
        exSheet.Cells[11, 16].Value = double.Parse(dt.Rows[5]["d12"].ToString());
        exSheet.Cells[11, 17].Value = double.Parse(dt.Rows[5]["d13"].ToString());
        exSheet.Cells[11, 18].Value = double.Parse(dt.Rows[5]["d14"].ToString());
        exSheet.Cells[11, 19].Value = double.Parse(dt.Rows[5]["d15"].ToString());
        exSheet.Cells[11, 20].Value = double.Parse(dt.Rows[5]["d16"].ToString());
        exSheet.Cells[11, 21].Value = double.Parse(dt.Rows[5]["d17"].ToString());
        exSheet.Cells[11, 22].Value = double.Parse(dt.Rows[5]["d18"].ToString());
        exSheet.Cells[11, 23].Value = double.Parse(dt.Rows[5]["d19"].ToString());
        exSheet.Cells[11, 24].Value = double.Parse(dt.Rows[5]["d20"].ToString());
        exSheet.Cells[11, 25].Value = double.Parse(dt.Rows[5]["d21"].ToString());
        exSheet.Cells[11, 26].Value = double.Parse(dt.Rows[5]["d22"].ToString());
        exSheet.Cells[11, 27].Value = double.Parse(dt.Rows[5]["d23"].ToString());
        exSheet.Cells[11, 28].Value = double.Parse(dt.Rows[5]["d24"].ToString());
        exSheet.Cells[11, 29].Value = double.Parse(dt.Rows[5]["d25"].ToString());
        exSheet.Cells[11, 30].Value = double.Parse(dt.Rows[5]["d26"].ToString());
        exSheet.Cells[11, 31].Value = double.Parse(dt.Rows[5]["d27"].ToString());
        exSheet.Cells[11, 32].Value = double.Parse(dt.Rows[5]["d28"].ToString());
        exSheet.Cells[11, 33].Value = double.Parse(dt.Rows[5]["d29"].ToString());
        exSheet.Cells[11, 34].Value = double.Parse(dt.Rows[5]["d30"].ToString());
        exSheet.Cells[11, 35].Value = double.Parse(dt.Rows[5]["d31"].ToString());

        exSheet.Cells[12, 3].Value = double.Parse(dt.Rows[6]["mm_sum"].ToString());
        exSheet.Cells[12, 4].Value = double.Parse(dt.Rows[6]["avg_month_amt"].ToString());
        exSheet.Cells[12, 5].Value = double.Parse(dt.Rows[6]["d1"].ToString());
        exSheet.Cells[12, 6].Value = double.Parse(dt.Rows[6]["d2"].ToString());
        exSheet.Cells[12, 7].Value = double.Parse(dt.Rows[6]["d3"].ToString());
        exSheet.Cells[12, 8].Value = double.Parse(dt.Rows[6]["d4"].ToString());
        exSheet.Cells[12, 9].Value = double.Parse(dt.Rows[6]["d5"].ToString());
        exSheet.Cells[12, 10].Value = double.Parse(dt.Rows[6]["d6"].ToString());
        exSheet.Cells[12, 11].Value = double.Parse(dt.Rows[6]["d7"].ToString());
        exSheet.Cells[12, 12].Value = double.Parse(dt.Rows[6]["d8"].ToString());
        exSheet.Cells[12, 13].Value = double.Parse(dt.Rows[6]["d9"].ToString());
        exSheet.Cells[12, 14].Value = double.Parse(dt.Rows[6]["d10"].ToString());
        exSheet.Cells[12, 15].Value = double.Parse(dt.Rows[6]["d11"].ToString());
        exSheet.Cells[12, 16].Value = double.Parse(dt.Rows[6]["d12"].ToString());
        exSheet.Cells[12, 17].Value = double.Parse(dt.Rows[6]["d13"].ToString());
        exSheet.Cells[12, 18].Value = double.Parse(dt.Rows[6]["d14"].ToString());
        exSheet.Cells[12, 19].Value = double.Parse(dt.Rows[6]["d15"].ToString());
        exSheet.Cells[12, 20].Value = double.Parse(dt.Rows[6]["d16"].ToString());
        exSheet.Cells[12, 21].Value = double.Parse(dt.Rows[6]["d17"].ToString());
        exSheet.Cells[12, 22].Value = double.Parse(dt.Rows[6]["d18"].ToString());
        exSheet.Cells[12, 23].Value = double.Parse(dt.Rows[6]["d19"].ToString());
        exSheet.Cells[12, 24].Value = double.Parse(dt.Rows[6]["d20"].ToString());
        exSheet.Cells[12, 25].Value = double.Parse(dt.Rows[6]["d21"].ToString());
        exSheet.Cells[12, 26].Value = double.Parse(dt.Rows[6]["d22"].ToString());
        exSheet.Cells[12, 27].Value = double.Parse(dt.Rows[6]["d23"].ToString());
        exSheet.Cells[12, 28].Value = double.Parse(dt.Rows[6]["d24"].ToString());
        exSheet.Cells[12, 29].Value = double.Parse(dt.Rows[6]["d25"].ToString());
        exSheet.Cells[12, 30].Value = double.Parse(dt.Rows[6]["d26"].ToString());
        exSheet.Cells[12, 31].Value = double.Parse(dt.Rows[6]["d27"].ToString());
        exSheet.Cells[12, 32].Value = double.Parse(dt.Rows[6]["d28"].ToString());
        exSheet.Cells[12, 33].Value = double.Parse(dt.Rows[6]["d29"].ToString());
        exSheet.Cells[12, 34].Value = double.Parse(dt.Rows[6]["d30"].ToString());
        exSheet.Cells[12, 35].Value = double.Parse(dt.Rows[6]["d31"].ToString());

        exSheet.Cells[13, 3].Value = double.Parse(dt.Rows[7]["mm_sum"].ToString());
        exSheet.Cells[13, 4].Value = double.Parse(dt.Rows[7]["avg_month_amt"].ToString());
        exSheet.Cells[13, 5].Value = double.Parse(dt.Rows[7]["d1"].ToString());
        exSheet.Cells[13, 6].Value = double.Parse(dt.Rows[7]["d2"].ToString());
        exSheet.Cells[13, 7].Value = double.Parse(dt.Rows[7]["d3"].ToString());
        exSheet.Cells[13, 8].Value = double.Parse(dt.Rows[7]["d4"].ToString());
        exSheet.Cells[13, 9].Value = double.Parse(dt.Rows[7]["d5"].ToString());
        exSheet.Cells[13, 10].Value = double.Parse(dt.Rows[7]["d6"].ToString());
        exSheet.Cells[13, 11].Value = double.Parse(dt.Rows[7]["d7"].ToString());
        exSheet.Cells[13, 12].Value = double.Parse(dt.Rows[7]["d8"].ToString());
        exSheet.Cells[13, 13].Value = double.Parse(dt.Rows[7]["d9"].ToString());
        exSheet.Cells[13, 14].Value = double.Parse(dt.Rows[7]["d10"].ToString());
        exSheet.Cells[13, 15].Value = double.Parse(dt.Rows[7]["d11"].ToString());
        exSheet.Cells[13, 16].Value = double.Parse(dt.Rows[7]["d12"].ToString());
        exSheet.Cells[13, 17].Value = double.Parse(dt.Rows[7]["d13"].ToString());
        exSheet.Cells[13, 18].Value = double.Parse(dt.Rows[7]["d14"].ToString());
        exSheet.Cells[13, 19].Value = double.Parse(dt.Rows[7]["d15"].ToString());
        exSheet.Cells[13, 20].Value = double.Parse(dt.Rows[7]["d16"].ToString());
        exSheet.Cells[13, 21].Value = double.Parse(dt.Rows[7]["d17"].ToString());
        exSheet.Cells[13, 22].Value = double.Parse(dt.Rows[7]["d18"].ToString());
        exSheet.Cells[13, 23].Value = double.Parse(dt.Rows[7]["d19"].ToString());
        exSheet.Cells[13, 24].Value = double.Parse(dt.Rows[7]["d20"].ToString());
        exSheet.Cells[13, 25].Value = double.Parse(dt.Rows[7]["d21"].ToString());
        exSheet.Cells[13, 26].Value = double.Parse(dt.Rows[7]["d22"].ToString());
        exSheet.Cells[13, 27].Value = double.Parse(dt.Rows[7]["d23"].ToString());
        exSheet.Cells[13, 28].Value = double.Parse(dt.Rows[7]["d24"].ToString());
        exSheet.Cells[13, 29].Value = double.Parse(dt.Rows[7]["d25"].ToString());
        exSheet.Cells[13, 30].Value = double.Parse(dt.Rows[7]["d26"].ToString());
        exSheet.Cells[13, 31].Value = double.Parse(dt.Rows[7]["d27"].ToString());
        exSheet.Cells[13, 32].Value = double.Parse(dt.Rows[7]["d28"].ToString());
        exSheet.Cells[13, 33].Value = double.Parse(dt.Rows[7]["d29"].ToString());
        exSheet.Cells[13, 34].Value = double.Parse(dt.Rows[7]["d30"].ToString());
        exSheet.Cells[13, 35].Value = double.Parse(dt.Rows[7]["d31"].ToString());

        exSheet.Cells[14, 3].Value = double.Parse(dt.Rows[8]["mm_sum"].ToString());
        exSheet.Cells[14, 4].Value = double.Parse(dt.Rows[8]["avg_month_amt"].ToString());
        exSheet.Cells[14, 5].Value = double.Parse(dt.Rows[8]["d1"].ToString());
        exSheet.Cells[14, 6].Value = double.Parse(dt.Rows[8]["d2"].ToString());
        exSheet.Cells[14, 7].Value = double.Parse(dt.Rows[8]["d3"].ToString());
        exSheet.Cells[14, 8].Value = double.Parse(dt.Rows[8]["d4"].ToString());
        exSheet.Cells[14, 9].Value = double.Parse(dt.Rows[8]["d5"].ToString());
        exSheet.Cells[14, 10].Value = double.Parse(dt.Rows[8]["d6"].ToString());
        exSheet.Cells[14, 11].Value = double.Parse(dt.Rows[8]["d7"].ToString());
        exSheet.Cells[14, 12].Value = double.Parse(dt.Rows[8]["d8"].ToString());
        exSheet.Cells[14, 13].Value = double.Parse(dt.Rows[8]["d9"].ToString());
        exSheet.Cells[14, 14].Value = double.Parse(dt.Rows[8]["d10"].ToString());
        exSheet.Cells[14, 15].Value = double.Parse(dt.Rows[8]["d11"].ToString());
        exSheet.Cells[14, 16].Value = double.Parse(dt.Rows[8]["d12"].ToString());
        exSheet.Cells[14, 17].Value = double.Parse(dt.Rows[8]["d13"].ToString());
        exSheet.Cells[14, 18].Value = double.Parse(dt.Rows[8]["d14"].ToString());
        exSheet.Cells[14, 19].Value = double.Parse(dt.Rows[8]["d15"].ToString());
        exSheet.Cells[14, 20].Value = double.Parse(dt.Rows[8]["d16"].ToString());
        exSheet.Cells[14, 21].Value = double.Parse(dt.Rows[8]["d17"].ToString());
        exSheet.Cells[14, 22].Value = double.Parse(dt.Rows[8]["d18"].ToString());
        exSheet.Cells[14, 23].Value = double.Parse(dt.Rows[8]["d19"].ToString());
        exSheet.Cells[14, 24].Value = double.Parse(dt.Rows[8]["d20"].ToString());
        exSheet.Cells[14, 25].Value = double.Parse(dt.Rows[8]["d21"].ToString());
        exSheet.Cells[14, 26].Value = double.Parse(dt.Rows[8]["d22"].ToString());
        exSheet.Cells[14, 27].Value = double.Parse(dt.Rows[8]["d23"].ToString());
        exSheet.Cells[14, 28].Value = double.Parse(dt.Rows[8]["d24"].ToString());
        exSheet.Cells[14, 29].Value = double.Parse(dt.Rows[8]["d25"].ToString());
        exSheet.Cells[14, 30].Value = double.Parse(dt.Rows[8]["d26"].ToString());
        exSheet.Cells[14, 31].Value = double.Parse(dt.Rows[8]["d27"].ToString());
        exSheet.Cells[14, 32].Value = double.Parse(dt.Rows[8]["d28"].ToString());
        exSheet.Cells[14, 33].Value = double.Parse(dt.Rows[8]["d29"].ToString());
        exSheet.Cells[14, 34].Value = double.Parse(dt.Rows[8]["d30"].ToString());
        exSheet.Cells[14, 35].Value = double.Parse(dt.Rows[8]["d31"].ToString());

        exSheet.Cells[15, 3].Value = double.Parse(dt.Rows[9]["mm_sum"].ToString());
        exSheet.Cells[15, 4].Value = double.Parse(dt.Rows[9]["avg_month_amt"].ToString());
        exSheet.Cells[15, 5].Value = double.Parse(dt.Rows[9]["d1"].ToString());
        exSheet.Cells[15, 6].Value = double.Parse(dt.Rows[9]["d2"].ToString());
        exSheet.Cells[15, 7].Value = double.Parse(dt.Rows[9]["d3"].ToString());
        exSheet.Cells[15, 8].Value = double.Parse(dt.Rows[9]["d4"].ToString());
        exSheet.Cells[15, 9].Value = double.Parse(dt.Rows[9]["d5"].ToString());
        exSheet.Cells[15, 10].Value = double.Parse(dt.Rows[9]["d6"].ToString());
        exSheet.Cells[15, 11].Value = double.Parse(dt.Rows[9]["d7"].ToString());
        exSheet.Cells[15, 12].Value = double.Parse(dt.Rows[9]["d8"].ToString());
        exSheet.Cells[15, 13].Value = double.Parse(dt.Rows[9]["d9"].ToString());
        exSheet.Cells[15, 14].Value = double.Parse(dt.Rows[9]["d10"].ToString());
        exSheet.Cells[15, 15].Value = double.Parse(dt.Rows[9]["d11"].ToString());
        exSheet.Cells[15, 16].Value = double.Parse(dt.Rows[9]["d12"].ToString());
        exSheet.Cells[15, 17].Value = double.Parse(dt.Rows[9]["d13"].ToString());
        exSheet.Cells[15, 18].Value = double.Parse(dt.Rows[9]["d14"].ToString());
        exSheet.Cells[15, 19].Value = double.Parse(dt.Rows[9]["d15"].ToString());
        exSheet.Cells[15, 20].Value = double.Parse(dt.Rows[9]["d16"].ToString());
        exSheet.Cells[15, 21].Value = double.Parse(dt.Rows[9]["d17"].ToString());
        exSheet.Cells[15, 22].Value = double.Parse(dt.Rows[9]["d18"].ToString());
        exSheet.Cells[15, 23].Value = double.Parse(dt.Rows[9]["d19"].ToString());
        exSheet.Cells[15, 24].Value = double.Parse(dt.Rows[9]["d20"].ToString());
        exSheet.Cells[15, 25].Value = double.Parse(dt.Rows[9]["d21"].ToString());
        exSheet.Cells[15, 26].Value = double.Parse(dt.Rows[9]["d22"].ToString());
        exSheet.Cells[15, 27].Value = double.Parse(dt.Rows[9]["d23"].ToString());
        exSheet.Cells[15, 28].Value = double.Parse(dt.Rows[9]["d24"].ToString());
        exSheet.Cells[15, 29].Value = double.Parse(dt.Rows[9]["d25"].ToString());
        exSheet.Cells[15, 30].Value = double.Parse(dt.Rows[9]["d26"].ToString());
        exSheet.Cells[15, 31].Value = double.Parse(dt.Rows[9]["d27"].ToString());
        exSheet.Cells[15, 32].Value = double.Parse(dt.Rows[9]["d28"].ToString());
        exSheet.Cells[15, 33].Value = double.Parse(dt.Rows[9]["d29"].ToString());
        exSheet.Cells[15, 34].Value = double.Parse(dt.Rows[9]["d30"].ToString());
        exSheet.Cells[15, 35].Value = double.Parse(dt.Rows[9]["d31"].ToString());

        exSheet.Cells[16, 3].Value = double.Parse(dt.Rows[10]["mm_sum"].ToString());
        exSheet.Cells[16, 4].Value = double.Parse(dt.Rows[10]["avg_month_amt"].ToString());
        exSheet.Cells[16, 5].Value = double.Parse(dt.Rows[10]["d1"].ToString());
        exSheet.Cells[16, 6].Value = double.Parse(dt.Rows[10]["d2"].ToString());
        exSheet.Cells[16, 7].Value = double.Parse(dt.Rows[10]["d3"].ToString());
        exSheet.Cells[16, 8].Value = double.Parse(dt.Rows[10]["d4"].ToString());
        exSheet.Cells[16, 9].Value = double.Parse(dt.Rows[10]["d5"].ToString());
        exSheet.Cells[16, 10].Value = double.Parse(dt.Rows[10]["d6"].ToString());
        exSheet.Cells[16, 11].Value = double.Parse(dt.Rows[10]["d7"].ToString());
        exSheet.Cells[61, 12].Value = double.Parse(dt.Rows[10]["d8"].ToString());
        exSheet.Cells[16, 13].Value = double.Parse(dt.Rows[10]["d9"].ToString());
        exSheet.Cells[16, 14].Value = double.Parse(dt.Rows[10]["d10"].ToString());
        exSheet.Cells[16, 15].Value = double.Parse(dt.Rows[10]["d11"].ToString());
        exSheet.Cells[16, 16].Value = double.Parse(dt.Rows[10]["d12"].ToString());
        exSheet.Cells[16, 17].Value = double.Parse(dt.Rows[10]["d13"].ToString());
        exSheet.Cells[16, 18].Value = double.Parse(dt.Rows[10]["d14"].ToString());
        exSheet.Cells[16, 19].Value = double.Parse(dt.Rows[10]["d15"].ToString());
        exSheet.Cells[16, 20].Value = double.Parse(dt.Rows[10]["d16"].ToString());
        exSheet.Cells[16, 21].Value = double.Parse(dt.Rows[10]["d17"].ToString());
        exSheet.Cells[16, 22].Value = double.Parse(dt.Rows[10]["d18"].ToString());
        exSheet.Cells[16, 23].Value = double.Parse(dt.Rows[10]["d19"].ToString());
        exSheet.Cells[16, 24].Value = double.Parse(dt.Rows[10]["d20"].ToString());
        exSheet.Cells[16, 25].Value = double.Parse(dt.Rows[10]["d21"].ToString());
        exSheet.Cells[16, 26].Value = double.Parse(dt.Rows[10]["d22"].ToString());
        exSheet.Cells[16, 27].Value = double.Parse(dt.Rows[10]["d23"].ToString());
        exSheet.Cells[16, 28].Value = double.Parse(dt.Rows[10]["d24"].ToString());
        exSheet.Cells[16, 29].Value = double.Parse(dt.Rows[10]["d25"].ToString());
        exSheet.Cells[16, 30].Value = double.Parse(dt.Rows[10]["d26"].ToString());
        exSheet.Cells[16, 31].Value = double.Parse(dt.Rows[10]["d27"].ToString());
        exSheet.Cells[16, 32].Value = double.Parse(dt.Rows[10]["d28"].ToString());
        exSheet.Cells[16, 33].Value = double.Parse(dt.Rows[10]["d29"].ToString());
        exSheet.Cells[16, 34].Value = double.Parse(dt.Rows[10]["d30"].ToString());
        exSheet.Cells[16, 35].Value = double.Parse(dt.Rows[10]["d31"].ToString());

        exSheet.Cells[17, 3].Value = double.Parse(dt.Rows[11]["mm_sum"].ToString());
        exSheet.Cells[17, 4].Value = double.Parse(dt.Rows[11]["avg_month_amt"].ToString());
        exSheet.Cells[17, 5].Value = double.Parse(dt.Rows[11]["d1"].ToString());
        exSheet.Cells[17, 6].Value = double.Parse(dt.Rows[11]["d2"].ToString());
        exSheet.Cells[17, 7].Value = double.Parse(dt.Rows[11]["d3"].ToString());
        exSheet.Cells[17, 8].Value = double.Parse(dt.Rows[11]["d4"].ToString());
        exSheet.Cells[17, 9].Value = double.Parse(dt.Rows[11]["d5"].ToString());
        exSheet.Cells[17, 10].Value = double.Parse(dt.Rows[11]["d6"].ToString());
        exSheet.Cells[17, 11].Value = double.Parse(dt.Rows[11]["d7"].ToString());
        exSheet.Cells[17, 12].Value = double.Parse(dt.Rows[11]["d8"].ToString());
        exSheet.Cells[17, 13].Value = double.Parse(dt.Rows[11]["d9"].ToString());
        exSheet.Cells[17, 14].Value = double.Parse(dt.Rows[11]["d10"].ToString());
        exSheet.Cells[17, 15].Value = double.Parse(dt.Rows[11]["d11"].ToString());
        exSheet.Cells[17, 16].Value = double.Parse(dt.Rows[11]["d12"].ToString());
        exSheet.Cells[17, 17].Value = double.Parse(dt.Rows[11]["d13"].ToString());
        exSheet.Cells[17, 18].Value = double.Parse(dt.Rows[11]["d14"].ToString());
        exSheet.Cells[17, 19].Value = double.Parse(dt.Rows[11]["d15"].ToString());
        exSheet.Cells[17, 20].Value = double.Parse(dt.Rows[11]["d16"].ToString());
        exSheet.Cells[17, 21].Value = double.Parse(dt.Rows[11]["d17"].ToString());
        exSheet.Cells[17, 22].Value = double.Parse(dt.Rows[11]["d18"].ToString());
        exSheet.Cells[17, 23].Value = double.Parse(dt.Rows[11]["d19"].ToString());
        exSheet.Cells[17, 24].Value = double.Parse(dt.Rows[11]["d20"].ToString());
        exSheet.Cells[17, 25].Value = double.Parse(dt.Rows[11]["d21"].ToString());
        exSheet.Cells[17, 26].Value = double.Parse(dt.Rows[11]["d22"].ToString());
        exSheet.Cells[17, 27].Value = double.Parse(dt.Rows[11]["d23"].ToString());
        exSheet.Cells[17, 28].Value = double.Parse(dt.Rows[11]["d24"].ToString());
        exSheet.Cells[17, 29].Value = double.Parse(dt.Rows[11]["d25"].ToString());
        exSheet.Cells[17, 30].Value = double.Parse(dt.Rows[11]["d26"].ToString());
        exSheet.Cells[17, 31].Value = double.Parse(dt.Rows[11]["d27"].ToString());
        exSheet.Cells[17, 32].Value = double.Parse(dt.Rows[11]["d28"].ToString());
        exSheet.Cells[17, 33].Value = double.Parse(dt.Rows[11]["d29"].ToString());
        exSheet.Cells[17, 34].Value = double.Parse(dt.Rows[11]["d30"].ToString());
        exSheet.Cells[17, 35].Value = double.Parse(dt.Rows[11]["d31"].ToString());

        exSheet.Cells[18, 3].Value = double.Parse(dt.Rows[12]["mm_sum"].ToString());
        exSheet.Cells[18, 4].Value = double.Parse(dt.Rows[12]["avg_month_amt"].ToString());
        exSheet.Cells[18, 5].Value = double.Parse(dt.Rows[12]["d1"].ToString());
        exSheet.Cells[18, 6].Value = double.Parse(dt.Rows[12]["d2"].ToString());
        exSheet.Cells[18, 7].Value = double.Parse(dt.Rows[12]["d3"].ToString());
        exSheet.Cells[18, 8].Value = double.Parse(dt.Rows[12]["d4"].ToString());
        exSheet.Cells[18, 9].Value = double.Parse(dt.Rows[12]["d5"].ToString());
        exSheet.Cells[18, 10].Value = double.Parse(dt.Rows[12]["d6"].ToString());
        exSheet.Cells[18, 11].Value = double.Parse(dt.Rows[12]["d7"].ToString());
        exSheet.Cells[18, 12].Value = double.Parse(dt.Rows[12]["d8"].ToString());
        exSheet.Cells[18, 13].Value = double.Parse(dt.Rows[12]["d9"].ToString());
        exSheet.Cells[18, 14].Value = double.Parse(dt.Rows[12]["d10"].ToString());
        exSheet.Cells[18, 15].Value = double.Parse(dt.Rows[12]["d11"].ToString());
        exSheet.Cells[18, 16].Value = double.Parse(dt.Rows[12]["d12"].ToString());
        exSheet.Cells[18, 17].Value = double.Parse(dt.Rows[12]["d13"].ToString());
        exSheet.Cells[18, 18].Value = double.Parse(dt.Rows[12]["d14"].ToString());
        exSheet.Cells[18, 19].Value = double.Parse(dt.Rows[12]["d15"].ToString());
        exSheet.Cells[18, 20].Value = double.Parse(dt.Rows[12]["d16"].ToString());
        exSheet.Cells[18, 21].Value = double.Parse(dt.Rows[12]["d17"].ToString());
        exSheet.Cells[18, 22].Value = double.Parse(dt.Rows[12]["d18"].ToString());
        exSheet.Cells[18, 23].Value = double.Parse(dt.Rows[12]["d19"].ToString());
        exSheet.Cells[18, 24].Value = double.Parse(dt.Rows[12]["d20"].ToString());
        exSheet.Cells[18, 25].Value = double.Parse(dt.Rows[12]["d21"].ToString());
        exSheet.Cells[18, 26].Value = double.Parse(dt.Rows[12]["d22"].ToString());
        exSheet.Cells[18, 27].Value = double.Parse(dt.Rows[12]["d23"].ToString());
        exSheet.Cells[18, 28].Value = double.Parse(dt.Rows[12]["d24"].ToString());
        exSheet.Cells[18, 29].Value = double.Parse(dt.Rows[12]["d25"].ToString());
        exSheet.Cells[18, 30].Value = double.Parse(dt.Rows[12]["d26"].ToString());
        exSheet.Cells[18, 31].Value = double.Parse(dt.Rows[12]["d27"].ToString());
        exSheet.Cells[18, 32].Value = double.Parse(dt.Rows[12]["d28"].ToString());
        exSheet.Cells[18, 33].Value = double.Parse(dt.Rows[12]["d29"].ToString());
        exSheet.Cells[18, 34].Value = double.Parse(dt.Rows[12]["d30"].ToString());
        exSheet.Cells[18, 35].Value = double.Parse(dt.Rows[12]["d31"].ToString());

        exSheet.Cells[19, 3].Value = double.Parse(dt.Rows[13]["mm_sum"].ToString());
        exSheet.Cells[19, 4].Value = double.Parse(dt.Rows[13]["avg_month_amt"].ToString());
        exSheet.Cells[19, 5].Value = double.Parse(dt.Rows[13]["d1"].ToString());
        exSheet.Cells[19, 6].Value = double.Parse(dt.Rows[13]["d2"].ToString());
        exSheet.Cells[19, 7].Value = double.Parse(dt.Rows[13]["d3"].ToString());
        exSheet.Cells[19, 8].Value = double.Parse(dt.Rows[13]["d4"].ToString());
        exSheet.Cells[19, 9].Value = double.Parse(dt.Rows[13]["d5"].ToString());
        exSheet.Cells[19, 10].Value = double.Parse(dt.Rows[13]["d6"].ToString());
        exSheet.Cells[19, 11].Value = double.Parse(dt.Rows[13]["d7"].ToString());
        exSheet.Cells[19, 12].Value = double.Parse(dt.Rows[13]["d8"].ToString());
        exSheet.Cells[19, 13].Value = double.Parse(dt.Rows[13]["d9"].ToString());
        exSheet.Cells[19, 14].Value = double.Parse(dt.Rows[13]["d10"].ToString());
        exSheet.Cells[19, 15].Value = double.Parse(dt.Rows[13]["d11"].ToString());
        exSheet.Cells[19, 16].Value = double.Parse(dt.Rows[13]["d12"].ToString());
        exSheet.Cells[19, 17].Value = double.Parse(dt.Rows[13]["d13"].ToString());
        exSheet.Cells[19, 18].Value = double.Parse(dt.Rows[13]["d14"].ToString());
        exSheet.Cells[19, 19].Value = double.Parse(dt.Rows[13]["d15"].ToString());
        exSheet.Cells[19, 20].Value = double.Parse(dt.Rows[13]["d16"].ToString());
        exSheet.Cells[19, 21].Value = double.Parse(dt.Rows[13]["d17"].ToString());
        exSheet.Cells[19, 22].Value = double.Parse(dt.Rows[13]["d18"].ToString());
        exSheet.Cells[19, 23].Value = double.Parse(dt.Rows[13]["d19"].ToString());
        exSheet.Cells[19, 24].Value = double.Parse(dt.Rows[13]["d20"].ToString());
        exSheet.Cells[19, 25].Value = double.Parse(dt.Rows[13]["d21"].ToString());
        exSheet.Cells[19, 26].Value = double.Parse(dt.Rows[13]["d22"].ToString());
        exSheet.Cells[19, 27].Value = double.Parse(dt.Rows[13]["d23"].ToString());
        exSheet.Cells[19, 28].Value = double.Parse(dt.Rows[13]["d24"].ToString());
        exSheet.Cells[19, 29].Value = double.Parse(dt.Rows[13]["d25"].ToString());
        exSheet.Cells[19, 30].Value = double.Parse(dt.Rows[13]["d26"].ToString());
        exSheet.Cells[19, 31].Value = double.Parse(dt.Rows[13]["d27"].ToString());
        exSheet.Cells[19, 32].Value = double.Parse(dt.Rows[13]["d28"].ToString());
        exSheet.Cells[19, 33].Value = double.Parse(dt.Rows[13]["d29"].ToString());
        exSheet.Cells[19, 34].Value = double.Parse(dt.Rows[13]["d30"].ToString());
        exSheet.Cells[19, 35].Value = double.Parse(dt.Rows[13]["d31"].ToString());

        exSheet.Cells[20, 3].Value = double.Parse(dt.Rows[14]["mm_sum"].ToString());
        exSheet.Cells[20, 4].Value = double.Parse(dt.Rows[14]["avg_month_amt"].ToString());
        exSheet.Cells[20, 5].Value = double.Parse(dt.Rows[14]["d1"].ToString());
        exSheet.Cells[20, 6].Value = double.Parse(dt.Rows[14]["d2"].ToString());
        exSheet.Cells[20, 7].Value = double.Parse(dt.Rows[14]["d3"].ToString());
        exSheet.Cells[20, 8].Value = double.Parse(dt.Rows[14]["d4"].ToString());
        exSheet.Cells[20, 9].Value = double.Parse(dt.Rows[14]["d5"].ToString());
        exSheet.Cells[20, 10].Value = double.Parse(dt.Rows[14]["d6"].ToString());
        exSheet.Cells[20, 11].Value = double.Parse(dt.Rows[14]["d7"].ToString());
        exSheet.Cells[20, 12].Value = double.Parse(dt.Rows[14]["d8"].ToString());
        exSheet.Cells[20, 13].Value = double.Parse(dt.Rows[14]["d9"].ToString());
        exSheet.Cells[20, 14].Value = double.Parse(dt.Rows[14]["d10"].ToString());
        exSheet.Cells[20, 15].Value = double.Parse(dt.Rows[14]["d11"].ToString());
        exSheet.Cells[20, 16].Value = double.Parse(dt.Rows[14]["d12"].ToString());
        exSheet.Cells[20, 17].Value = double.Parse(dt.Rows[14]["d13"].ToString());
        exSheet.Cells[20, 18].Value = double.Parse(dt.Rows[14]["d14"].ToString());
        exSheet.Cells[20, 19].Value = double.Parse(dt.Rows[14]["d15"].ToString());
        exSheet.Cells[20, 20].Value = double.Parse(dt.Rows[14]["d16"].ToString());
        exSheet.Cells[20, 21].Value = double.Parse(dt.Rows[14]["d17"].ToString());
        exSheet.Cells[20, 22].Value = double.Parse(dt.Rows[14]["d18"].ToString());
        exSheet.Cells[20, 23].Value = double.Parse(dt.Rows[14]["d19"].ToString());
        exSheet.Cells[20, 24].Value = double.Parse(dt.Rows[14]["d20"].ToString());
        exSheet.Cells[20, 25].Value = double.Parse(dt.Rows[14]["d21"].ToString());
        exSheet.Cells[20, 26].Value = double.Parse(dt.Rows[14]["d22"].ToString());
        exSheet.Cells[20, 27].Value = double.Parse(dt.Rows[14]["d23"].ToString());
        exSheet.Cells[20, 28].Value = double.Parse(dt.Rows[14]["d24"].ToString());
        exSheet.Cells[20, 29].Value = double.Parse(dt.Rows[14]["d25"].ToString());
        exSheet.Cells[20, 30].Value = double.Parse(dt.Rows[14]["d26"].ToString());
        exSheet.Cells[20, 31].Value = double.Parse(dt.Rows[14]["d27"].ToString());
        exSheet.Cells[20, 32].Value = double.Parse(dt.Rows[14]["d28"].ToString());
        exSheet.Cells[20, 33].Value = double.Parse(dt.Rows[14]["d29"].ToString());
        exSheet.Cells[20, 34].Value = double.Parse(dt.Rows[14]["d30"].ToString());
        exSheet.Cells[20, 35].Value = double.Parse(dt.Rows[14]["d31"].ToString());

        exSheet.Cells[21, 3].Value = double.Parse(dt.Rows[15]["mm_sum"].ToString());
        exSheet.Cells[21, 4].Value = double.Parse(dt.Rows[15]["avg_month_amt"].ToString());
        exSheet.Cells[21, 5].Value = double.Parse(dt.Rows[15]["d1"].ToString());
        exSheet.Cells[21, 6].Value = double.Parse(dt.Rows[15]["d2"].ToString());
        exSheet.Cells[21, 7].Value = double.Parse(dt.Rows[15]["d3"].ToString());
        exSheet.Cells[21, 8].Value = double.Parse(dt.Rows[15]["d4"].ToString());
        exSheet.Cells[21, 9].Value = double.Parse(dt.Rows[15]["d5"].ToString());
        exSheet.Cells[21, 10].Value = double.Parse(dt.Rows[15]["d6"].ToString());
        exSheet.Cells[21, 11].Value = double.Parse(dt.Rows[15]["d7"].ToString());
        exSheet.Cells[21, 12].Value = double.Parse(dt.Rows[15]["d8"].ToString());
        exSheet.Cells[21, 13].Value = double.Parse(dt.Rows[15]["d9"].ToString());
        exSheet.Cells[21, 14].Value = double.Parse(dt.Rows[15]["d10"].ToString());
        exSheet.Cells[21, 15].Value = double.Parse(dt.Rows[15]["d11"].ToString());
        exSheet.Cells[21, 16].Value = double.Parse(dt.Rows[15]["d12"].ToString());
        exSheet.Cells[21, 17].Value = double.Parse(dt.Rows[15]["d13"].ToString());
        exSheet.Cells[21, 18].Value = double.Parse(dt.Rows[15]["d14"].ToString());
        exSheet.Cells[21, 19].Value = double.Parse(dt.Rows[15]["d15"].ToString());
        exSheet.Cells[21, 20].Value = double.Parse(dt.Rows[15]["d16"].ToString());
        exSheet.Cells[21, 21].Value = double.Parse(dt.Rows[15]["d17"].ToString());
        exSheet.Cells[21, 22].Value = double.Parse(dt.Rows[15]["d18"].ToString());
        exSheet.Cells[21, 23].Value = double.Parse(dt.Rows[15]["d19"].ToString());
        exSheet.Cells[21, 24].Value = double.Parse(dt.Rows[15]["d20"].ToString());
        exSheet.Cells[21, 25].Value = double.Parse(dt.Rows[15]["d21"].ToString());
        exSheet.Cells[21, 26].Value = double.Parse(dt.Rows[15]["d22"].ToString());
        exSheet.Cells[21, 27].Value = double.Parse(dt.Rows[15]["d23"].ToString());
        exSheet.Cells[21, 28].Value = double.Parse(dt.Rows[15]["d24"].ToString());
        exSheet.Cells[21, 29].Value = double.Parse(dt.Rows[15]["d25"].ToString());
        exSheet.Cells[21, 30].Value = double.Parse(dt.Rows[15]["d26"].ToString());
        exSheet.Cells[21, 31].Value = double.Parse(dt.Rows[15]["d27"].ToString());
        exSheet.Cells[21, 32].Value = double.Parse(dt.Rows[15]["d28"].ToString());
        exSheet.Cells[21, 33].Value = double.Parse(dt.Rows[15]["d29"].ToString());
        exSheet.Cells[21, 34].Value = double.Parse(dt.Rows[15]["d30"].ToString());
        exSheet.Cells[21, 35].Value = double.Parse(dt.Rows[15]["d31"].ToString());

        exSheet.Cells[22, 3].Value = double.Parse(dt.Rows[16]["mm_sum"].ToString());
        exSheet.Cells[22, 4].Value = double.Parse(dt.Rows[16]["avg_month_amt"].ToString());
        exSheet.Cells[22, 5].Value = double.Parse(dt.Rows[16]["d1"].ToString());
        exSheet.Cells[22, 6].Value = double.Parse(dt.Rows[16]["d2"].ToString());
        exSheet.Cells[22, 7].Value = double.Parse(dt.Rows[16]["d3"].ToString());
        exSheet.Cells[22, 8].Value = double.Parse(dt.Rows[16]["d4"].ToString());
        exSheet.Cells[22, 9].Value = double.Parse(dt.Rows[16]["d5"].ToString());
        exSheet.Cells[22, 10].Value = double.Parse(dt.Rows[16]["d6"].ToString());
        exSheet.Cells[22, 11].Value = double.Parse(dt.Rows[16]["d7"].ToString());
        exSheet.Cells[22, 12].Value = double.Parse(dt.Rows[16]["d8"].ToString());
        exSheet.Cells[22, 13].Value = double.Parse(dt.Rows[16]["d9"].ToString());
        exSheet.Cells[22, 14].Value = double.Parse(dt.Rows[16]["d10"].ToString());
        exSheet.Cells[22, 15].Value = double.Parse(dt.Rows[16]["d11"].ToString());
        exSheet.Cells[22, 16].Value = double.Parse(dt.Rows[16]["d12"].ToString());
        exSheet.Cells[22, 17].Value = double.Parse(dt.Rows[16]["d13"].ToString());
        exSheet.Cells[22, 18].Value = double.Parse(dt.Rows[16]["d14"].ToString());
        exSheet.Cells[22, 19].Value = double.Parse(dt.Rows[16]["d15"].ToString());
        exSheet.Cells[22, 20].Value = double.Parse(dt.Rows[16]["d16"].ToString());
        exSheet.Cells[22, 21].Value = double.Parse(dt.Rows[16]["d17"].ToString());
        exSheet.Cells[22, 22].Value = double.Parse(dt.Rows[16]["d18"].ToString());
        exSheet.Cells[22, 23].Value = double.Parse(dt.Rows[16]["d19"].ToString());
        exSheet.Cells[22, 24].Value = double.Parse(dt.Rows[16]["d20"].ToString());
        exSheet.Cells[22, 25].Value = double.Parse(dt.Rows[16]["d21"].ToString());
        exSheet.Cells[22, 26].Value = double.Parse(dt.Rows[16]["d22"].ToString());
        exSheet.Cells[22, 27].Value = double.Parse(dt.Rows[16]["d23"].ToString());
        exSheet.Cells[22, 28].Value = double.Parse(dt.Rows[16]["d24"].ToString());
        exSheet.Cells[22, 29].Value = double.Parse(dt.Rows[16]["d25"].ToString());
        exSheet.Cells[22, 30].Value = double.Parse(dt.Rows[16]["d26"].ToString());
        exSheet.Cells[22, 31].Value = double.Parse(dt.Rows[16]["d27"].ToString());
        exSheet.Cells[22, 32].Value = double.Parse(dt.Rows[16]["d28"].ToString());
        exSheet.Cells[22, 33].Value = double.Parse(dt.Rows[16]["d29"].ToString());
        exSheet.Cells[22, 34].Value = double.Parse(dt.Rows[16]["d30"].ToString());
        exSheet.Cells[22, 35].Value = double.Parse(dt.Rows[16]["d31"].ToString());

        exSheet.Cells[23, 3].Value = double.Parse(dt.Rows[17]["mm_sum"].ToString());
        exSheet.Cells[23, 4].Value = double.Parse(dt.Rows[17]["avg_month_amt"].ToString());
        exSheet.Cells[23, 5].Value = double.Parse(dt.Rows[17]["d1"].ToString());
        exSheet.Cells[23, 6].Value = double.Parse(dt.Rows[17]["d2"].ToString());
        exSheet.Cells[23, 7].Value = double.Parse(dt.Rows[17]["d3"].ToString());
        exSheet.Cells[23, 8].Value = double.Parse(dt.Rows[17]["d4"].ToString());
        exSheet.Cells[23, 9].Value = double.Parse(dt.Rows[17]["d5"].ToString());
        exSheet.Cells[23, 10].Value = double.Parse(dt.Rows[17]["d6"].ToString());
        exSheet.Cells[23, 11].Value = double.Parse(dt.Rows[17]["d7"].ToString());
        exSheet.Cells[23, 12].Value = double.Parse(dt.Rows[17]["d8"].ToString());
        exSheet.Cells[23, 13].Value = double.Parse(dt.Rows[17]["d9"].ToString());
        exSheet.Cells[23, 14].Value = double.Parse(dt.Rows[17]["d10"].ToString());
        exSheet.Cells[23, 15].Value = double.Parse(dt.Rows[17]["d11"].ToString());
        exSheet.Cells[23, 16].Value = double.Parse(dt.Rows[17]["d12"].ToString());
        exSheet.Cells[23, 17].Value = double.Parse(dt.Rows[17]["d13"].ToString());
        exSheet.Cells[23, 18].Value = double.Parse(dt.Rows[17]["d14"].ToString());
        exSheet.Cells[23, 19].Value = double.Parse(dt.Rows[17]["d15"].ToString());
        exSheet.Cells[23, 20].Value = double.Parse(dt.Rows[17]["d16"].ToString());
        exSheet.Cells[23, 21].Value = double.Parse(dt.Rows[17]["d17"].ToString());
        exSheet.Cells[23, 22].Value = double.Parse(dt.Rows[17]["d18"].ToString());
        exSheet.Cells[23, 23].Value = double.Parse(dt.Rows[17]["d19"].ToString());
        exSheet.Cells[23, 24].Value = double.Parse(dt.Rows[17]["d20"].ToString());
        exSheet.Cells[23, 25].Value = double.Parse(dt.Rows[17]["d21"].ToString());
        exSheet.Cells[23, 26].Value = double.Parse(dt.Rows[17]["d22"].ToString());
        exSheet.Cells[23, 27].Value = double.Parse(dt.Rows[17]["d23"].ToString());
        exSheet.Cells[23, 28].Value = double.Parse(dt.Rows[17]["d24"].ToString());
        exSheet.Cells[23, 29].Value = double.Parse(dt.Rows[17]["d25"].ToString());
        exSheet.Cells[23, 30].Value = double.Parse(dt.Rows[17]["d26"].ToString());
        exSheet.Cells[23, 31].Value = double.Parse(dt.Rows[17]["d27"].ToString());
        exSheet.Cells[23, 32].Value = double.Parse(dt.Rows[17]["d28"].ToString());
        exSheet.Cells[23, 33].Value = double.Parse(dt.Rows[17]["d29"].ToString());
        exSheet.Cells[23, 34].Value = double.Parse(dt.Rows[17]["d30"].ToString());
        exSheet.Cells[23, 35].Value = double.Parse(dt.Rows[17]["d31"].ToString());

        exSheet.Cells[24, 3].Value = double.Parse(dt.Rows[18]["mm_sum"].ToString());
        exSheet.Cells[24, 4].Value = double.Parse(dt.Rows[18]["avg_month_amt"].ToString());
        exSheet.Cells[24, 5].Value = double.Parse(dt.Rows[18]["d1"].ToString());
        exSheet.Cells[24, 6].Value = double.Parse(dt.Rows[18]["d2"].ToString());
        exSheet.Cells[24, 7].Value = double.Parse(dt.Rows[18]["d3"].ToString());
        exSheet.Cells[24, 8].Value = double.Parse(dt.Rows[18]["d4"].ToString());
        exSheet.Cells[24, 9].Value = double.Parse(dt.Rows[18]["d5"].ToString());
        exSheet.Cells[24, 10].Value = double.Parse(dt.Rows[18]["d6"].ToString());
        exSheet.Cells[24, 11].Value = double.Parse(dt.Rows[18]["d7"].ToString());
        exSheet.Cells[24, 12].Value = double.Parse(dt.Rows[18]["d8"].ToString());
        exSheet.Cells[24, 13].Value = double.Parse(dt.Rows[18]["d9"].ToString());
        exSheet.Cells[24, 14].Value = double.Parse(dt.Rows[18]["d10"].ToString());
        exSheet.Cells[24, 15].Value = double.Parse(dt.Rows[18]["d11"].ToString());
        exSheet.Cells[24, 16].Value = double.Parse(dt.Rows[18]["d12"].ToString());
        exSheet.Cells[24, 17].Value = double.Parse(dt.Rows[18]["d13"].ToString());
        exSheet.Cells[24, 18].Value = double.Parse(dt.Rows[18]["d14"].ToString());
        exSheet.Cells[24, 19].Value = double.Parse(dt.Rows[18]["d15"].ToString());
        exSheet.Cells[24, 20].Value = double.Parse(dt.Rows[18]["d16"].ToString());
        exSheet.Cells[24, 21].Value = double.Parse(dt.Rows[18]["d17"].ToString());
        exSheet.Cells[24, 22].Value = double.Parse(dt.Rows[18]["d18"].ToString());
        exSheet.Cells[24, 23].Value = double.Parse(dt.Rows[18]["d19"].ToString());
        exSheet.Cells[24, 24].Value = double.Parse(dt.Rows[18]["d20"].ToString());
        exSheet.Cells[24, 25].Value = double.Parse(dt.Rows[18]["d21"].ToString());
        exSheet.Cells[24, 26].Value = double.Parse(dt.Rows[18]["d22"].ToString());
        exSheet.Cells[24, 27].Value = double.Parse(dt.Rows[18]["d23"].ToString());
        exSheet.Cells[24, 28].Value = double.Parse(dt.Rows[18]["d24"].ToString());
        exSheet.Cells[24, 29].Value = double.Parse(dt.Rows[18]["d25"].ToString());
        exSheet.Cells[24, 30].Value = double.Parse(dt.Rows[18]["d26"].ToString());
        exSheet.Cells[24, 31].Value = double.Parse(dt.Rows[18]["d27"].ToString());
        exSheet.Cells[24, 32].Value = double.Parse(dt.Rows[18]["d28"].ToString());
        exSheet.Cells[24, 33].Value = double.Parse(dt.Rows[18]["d29"].ToString());
        exSheet.Cells[24, 34].Value = double.Parse(dt.Rows[18]["d30"].ToString());
        exSheet.Cells[24, 35].Value = double.Parse(dt.Rows[18]["d31"].ToString());

        exSheet.Cells[25, 3].Value = double.Parse(dt.Rows[19]["mm_sum"].ToString());
        exSheet.Cells[25, 4].Value = double.Parse(dt.Rows[19]["avg_month_amt"].ToString());
        exSheet.Cells[25, 5].Value = double.Parse(dt.Rows[19]["d1"].ToString());
        exSheet.Cells[25, 6].Value = double.Parse(dt.Rows[19]["d2"].ToString());
        exSheet.Cells[25, 7].Value = double.Parse(dt.Rows[19]["d3"].ToString());
        exSheet.Cells[25, 8].Value = double.Parse(dt.Rows[19]["d4"].ToString());
        exSheet.Cells[25, 9].Value = double.Parse(dt.Rows[19]["d5"].ToString());
        exSheet.Cells[25, 10].Value = double.Parse(dt.Rows[19]["d6"].ToString());
        exSheet.Cells[25, 11].Value = double.Parse(dt.Rows[19]["d7"].ToString());
        exSheet.Cells[25, 12].Value = double.Parse(dt.Rows[19]["d8"].ToString());
        exSheet.Cells[25, 13].Value = double.Parse(dt.Rows[19]["d9"].ToString());
        exSheet.Cells[25, 14].Value = double.Parse(dt.Rows[19]["d10"].ToString());
        exSheet.Cells[25, 15].Value = double.Parse(dt.Rows[19]["d11"].ToString());
        exSheet.Cells[25, 16].Value = double.Parse(dt.Rows[19]["d12"].ToString());
        exSheet.Cells[25, 17].Value = double.Parse(dt.Rows[19]["d13"].ToString());
        exSheet.Cells[25, 18].Value = double.Parse(dt.Rows[19]["d14"].ToString());
        exSheet.Cells[25, 19].Value = double.Parse(dt.Rows[19]["d15"].ToString());
        exSheet.Cells[25, 20].Value = double.Parse(dt.Rows[19]["d16"].ToString());
        exSheet.Cells[25, 21].Value = double.Parse(dt.Rows[19]["d17"].ToString());
        exSheet.Cells[25, 22].Value = double.Parse(dt.Rows[19]["d18"].ToString());
        exSheet.Cells[25, 23].Value = double.Parse(dt.Rows[19]["d19"].ToString());
        exSheet.Cells[25, 24].Value = double.Parse(dt.Rows[19]["d20"].ToString());
        exSheet.Cells[25, 25].Value = double.Parse(dt.Rows[19]["d21"].ToString());
        exSheet.Cells[25, 26].Value = double.Parse(dt.Rows[19]["d22"].ToString());
        exSheet.Cells[25, 27].Value = double.Parse(dt.Rows[19]["d23"].ToString());
        exSheet.Cells[25, 28].Value = double.Parse(dt.Rows[19]["d24"].ToString());
        exSheet.Cells[25, 29].Value = double.Parse(dt.Rows[19]["d25"].ToString());
        exSheet.Cells[25, 30].Value = double.Parse(dt.Rows[19]["d26"].ToString());
        exSheet.Cells[25, 31].Value = double.Parse(dt.Rows[19]["d27"].ToString());
        exSheet.Cells[25, 32].Value = double.Parse(dt.Rows[19]["d28"].ToString());
        exSheet.Cells[25, 33].Value = double.Parse(dt.Rows[19]["d29"].ToString());
        exSheet.Cells[25, 34].Value = double.Parse(dt.Rows[19]["d30"].ToString());
        exSheet.Cells[25, 35].Value = double.Parse(dt.Rows[19]["d31"].ToString());

        exSheet.Cells[26, 3].Value = double.Parse(dt.Rows[20]["mm_sum"].ToString());
        exSheet.Cells[26, 4].Value = double.Parse(dt.Rows[20]["avg_month_amt"].ToString());
        exSheet.Cells[26, 5].Value = double.Parse(dt.Rows[20]["d1"].ToString());
        exSheet.Cells[26, 6].Value = double.Parse(dt.Rows[20]["d2"].ToString());
        exSheet.Cells[26, 7].Value = double.Parse(dt.Rows[20]["d3"].ToString());
        exSheet.Cells[26, 8].Value = double.Parse(dt.Rows[20]["d4"].ToString());
        exSheet.Cells[26, 9].Value = double.Parse(dt.Rows[20]["d5"].ToString());
        exSheet.Cells[26, 10].Value = double.Parse(dt.Rows[20]["d6"].ToString());
        exSheet.Cells[26, 11].Value = double.Parse(dt.Rows[20]["d7"].ToString());
        exSheet.Cells[26, 12].Value = double.Parse(dt.Rows[20]["d8"].ToString());
        exSheet.Cells[26, 13].Value = double.Parse(dt.Rows[20]["d9"].ToString());
        exSheet.Cells[26, 14].Value = double.Parse(dt.Rows[20]["d10"].ToString());
        exSheet.Cells[26, 15].Value = double.Parse(dt.Rows[20]["d11"].ToString());
        exSheet.Cells[26, 16].Value = double.Parse(dt.Rows[20]["d12"].ToString());
        exSheet.Cells[26, 17].Value = double.Parse(dt.Rows[20]["d13"].ToString());
        exSheet.Cells[26, 18].Value = double.Parse(dt.Rows[20]["d14"].ToString());
        exSheet.Cells[26, 19].Value = double.Parse(dt.Rows[20]["d15"].ToString());
        exSheet.Cells[26, 20].Value = double.Parse(dt.Rows[20]["d16"].ToString());
        exSheet.Cells[26, 21].Value = double.Parse(dt.Rows[20]["d17"].ToString());
        exSheet.Cells[26, 22].Value = double.Parse(dt.Rows[20]["d18"].ToString());
        exSheet.Cells[26, 23].Value = double.Parse(dt.Rows[20]["d19"].ToString());
        exSheet.Cells[26, 24].Value = double.Parse(dt.Rows[20]["d20"].ToString());
        exSheet.Cells[26, 25].Value = double.Parse(dt.Rows[20]["d21"].ToString());
        exSheet.Cells[26, 26].Value = double.Parse(dt.Rows[20]["d22"].ToString());
        exSheet.Cells[26, 27].Value = double.Parse(dt.Rows[20]["d23"].ToString());
        exSheet.Cells[26, 28].Value = double.Parse(dt.Rows[20]["d24"].ToString());
        exSheet.Cells[26, 29].Value = double.Parse(dt.Rows[20]["d25"].ToString());
        exSheet.Cells[26, 30].Value = double.Parse(dt.Rows[20]["d26"].ToString());
        exSheet.Cells[26, 31].Value = double.Parse(dt.Rows[20]["d27"].ToString());
        exSheet.Cells[26, 32].Value = double.Parse(dt.Rows[20]["d28"].ToString());
        exSheet.Cells[26, 33].Value = double.Parse(dt.Rows[20]["d29"].ToString());
        exSheet.Cells[26, 34].Value = double.Parse(dt.Rows[20]["d30"].ToString());
        exSheet.Cells[26, 35].Value = double.Parse(dt.Rows[20]["d31"].ToString());

        exSheet.Cells[27, 3].Value = double.Parse(dt.Rows[21]["mm_sum"].ToString());
        exSheet.Cells[27, 4].Value = double.Parse(dt.Rows[21]["avg_month_amt"].ToString());
        exSheet.Cells[27, 5].Value = double.Parse(dt.Rows[21]["d1"].ToString());
        exSheet.Cells[27, 6].Value = double.Parse(dt.Rows[21]["d2"].ToString());
        exSheet.Cells[27, 7].Value = double.Parse(dt.Rows[21]["d3"].ToString());
        exSheet.Cells[27, 8].Value = double.Parse(dt.Rows[21]["d4"].ToString());
        exSheet.Cells[27, 9].Value = double.Parse(dt.Rows[21]["d5"].ToString());
        exSheet.Cells[27, 10].Value = double.Parse(dt.Rows[21]["d6"].ToString());
        exSheet.Cells[27, 11].Value = double.Parse(dt.Rows[21]["d7"].ToString());
        exSheet.Cells[27, 12].Value = double.Parse(dt.Rows[21]["d8"].ToString());
        exSheet.Cells[27, 13].Value = double.Parse(dt.Rows[21]["d9"].ToString());
        exSheet.Cells[27, 14].Value = double.Parse(dt.Rows[21]["d10"].ToString());
        exSheet.Cells[27, 15].Value = double.Parse(dt.Rows[21]["d11"].ToString());
        exSheet.Cells[27, 16].Value = double.Parse(dt.Rows[21]["d12"].ToString());
        exSheet.Cells[27, 17].Value = double.Parse(dt.Rows[21]["d13"].ToString());
        exSheet.Cells[27, 18].Value = double.Parse(dt.Rows[21]["d14"].ToString());
        exSheet.Cells[27, 19].Value = double.Parse(dt.Rows[21]["d15"].ToString());
        exSheet.Cells[27, 20].Value = double.Parse(dt.Rows[21]["d16"].ToString());
        exSheet.Cells[27, 21].Value = double.Parse(dt.Rows[21]["d17"].ToString());
        exSheet.Cells[27, 22].Value = double.Parse(dt.Rows[21]["d18"].ToString());
        exSheet.Cells[27, 23].Value = double.Parse(dt.Rows[21]["d19"].ToString());
        exSheet.Cells[27, 24].Value = double.Parse(dt.Rows[21]["d20"].ToString());
        exSheet.Cells[27, 25].Value = double.Parse(dt.Rows[21]["d21"].ToString());
        exSheet.Cells[27, 26].Value = double.Parse(dt.Rows[21]["d22"].ToString());
        exSheet.Cells[27, 27].Value = double.Parse(dt.Rows[21]["d23"].ToString());
        exSheet.Cells[27, 28].Value = double.Parse(dt.Rows[21]["d24"].ToString());
        exSheet.Cells[27, 29].Value = double.Parse(dt.Rows[21]["d25"].ToString());
        exSheet.Cells[27, 30].Value = double.Parse(dt.Rows[21]["d26"].ToString());
        exSheet.Cells[27, 31].Value = double.Parse(dt.Rows[21]["d27"].ToString());
        exSheet.Cells[27, 32].Value = double.Parse(dt.Rows[21]["d28"].ToString());
        exSheet.Cells[27, 33].Value = double.Parse(dt.Rows[21]["d29"].ToString());
        exSheet.Cells[27, 34].Value = double.Parse(dt.Rows[21]["d30"].ToString());
        exSheet.Cells[27, 35].Value = double.Parse(dt.Rows[21]["d31"].ToString());

        exSheet.Cells[28, 3].Value = double.Parse(dt.Rows[22]["mm_sum"].ToString());
        exSheet.Cells[28, 4].Value = double.Parse(dt.Rows[22]["avg_month_amt"].ToString());
        exSheet.Cells[28, 5].Value = double.Parse(dt.Rows[22]["d1"].ToString());
        exSheet.Cells[28, 6].Value = double.Parse(dt.Rows[22]["d2"].ToString());
        exSheet.Cells[28, 7].Value = double.Parse(dt.Rows[22]["d3"].ToString());
        exSheet.Cells[28, 8].Value = double.Parse(dt.Rows[22]["d4"].ToString());
        exSheet.Cells[28, 9].Value = double.Parse(dt.Rows[22]["d5"].ToString());
        exSheet.Cells[28, 10].Value = double.Parse(dt.Rows[22]["d6"].ToString());
        exSheet.Cells[28, 11].Value = double.Parse(dt.Rows[22]["d7"].ToString());
        exSheet.Cells[28, 12].Value = double.Parse(dt.Rows[22]["d8"].ToString());
        exSheet.Cells[28, 13].Value = double.Parse(dt.Rows[22]["d9"].ToString());
        exSheet.Cells[28, 14].Value = double.Parse(dt.Rows[22]["d10"].ToString());
        exSheet.Cells[28, 15].Value = double.Parse(dt.Rows[22]["d11"].ToString());
        exSheet.Cells[28, 16].Value = double.Parse(dt.Rows[22]["d12"].ToString());
        exSheet.Cells[28, 17].Value = double.Parse(dt.Rows[22]["d13"].ToString());
        exSheet.Cells[28, 18].Value = double.Parse(dt.Rows[22]["d14"].ToString());
        exSheet.Cells[28, 19].Value = double.Parse(dt.Rows[22]["d15"].ToString());
        exSheet.Cells[28, 20].Value = double.Parse(dt.Rows[22]["d16"].ToString());
        exSheet.Cells[28, 21].Value = double.Parse(dt.Rows[22]["d17"].ToString());
        exSheet.Cells[28, 22].Value = double.Parse(dt.Rows[22]["d18"].ToString());
        exSheet.Cells[28, 23].Value = double.Parse(dt.Rows[22]["d19"].ToString());
        exSheet.Cells[28, 24].Value = double.Parse(dt.Rows[22]["d20"].ToString());
        exSheet.Cells[28, 25].Value = double.Parse(dt.Rows[22]["d21"].ToString());
        exSheet.Cells[28, 26].Value = double.Parse(dt.Rows[22]["d22"].ToString());
        exSheet.Cells[28, 27].Value = double.Parse(dt.Rows[22]["d23"].ToString());
        exSheet.Cells[28, 28].Value = double.Parse(dt.Rows[22]["d24"].ToString());
        exSheet.Cells[28, 29].Value = double.Parse(dt.Rows[22]["d25"].ToString());
        exSheet.Cells[28, 30].Value = double.Parse(dt.Rows[22]["d26"].ToString());
        exSheet.Cells[28, 31].Value = double.Parse(dt.Rows[22]["d27"].ToString());
        exSheet.Cells[28, 32].Value = double.Parse(dt.Rows[22]["d28"].ToString());
        exSheet.Cells[28, 33].Value = double.Parse(dt.Rows[22]["d29"].ToString());
        exSheet.Cells[28, 34].Value = double.Parse(dt.Rows[22]["d30"].ToString());
        exSheet.Cells[28, 35].Value = double.Parse(dt.Rows[22]["d31"].ToString());

        exSheet.Cells[29, 3].Value = double.Parse(dt.Rows[23]["mm_sum"].ToString());
        exSheet.Cells[29, 4].Value = double.Parse(dt.Rows[23]["avg_month_amt"].ToString());
        exSheet.Cells[29, 5].Value = double.Parse(dt.Rows[23]["d1"].ToString());
        exSheet.Cells[29, 6].Value = double.Parse(dt.Rows[23]["d2"].ToString());
        exSheet.Cells[29, 7].Value = double.Parse(dt.Rows[23]["d3"].ToString());
        exSheet.Cells[29, 8].Value = double.Parse(dt.Rows[23]["d4"].ToString());
        exSheet.Cells[29, 9].Value = double.Parse(dt.Rows[23]["d5"].ToString());
        exSheet.Cells[29, 10].Value = double.Parse(dt.Rows[23]["d6"].ToString());
        exSheet.Cells[29, 11].Value = double.Parse(dt.Rows[23]["d7"].ToString());
        exSheet.Cells[29, 12].Value = double.Parse(dt.Rows[23]["d8"].ToString());
        exSheet.Cells[29, 13].Value = double.Parse(dt.Rows[23]["d9"].ToString());
        exSheet.Cells[29, 14].Value = double.Parse(dt.Rows[23]["d10"].ToString());
        exSheet.Cells[29, 15].Value = double.Parse(dt.Rows[23]["d11"].ToString());
        exSheet.Cells[29, 16].Value = double.Parse(dt.Rows[23]["d12"].ToString());
        exSheet.Cells[29, 17].Value = double.Parse(dt.Rows[23]["d13"].ToString());
        exSheet.Cells[29, 18].Value = double.Parse(dt.Rows[23]["d14"].ToString());
        exSheet.Cells[29, 19].Value = double.Parse(dt.Rows[23]["d15"].ToString());
        exSheet.Cells[29, 20].Value = double.Parse(dt.Rows[23]["d16"].ToString());
        exSheet.Cells[29, 21].Value = double.Parse(dt.Rows[23]["d17"].ToString());
        exSheet.Cells[29, 22].Value = double.Parse(dt.Rows[23]["d18"].ToString());
        exSheet.Cells[29, 23].Value = double.Parse(dt.Rows[23]["d19"].ToString());
        exSheet.Cells[29, 24].Value = double.Parse(dt.Rows[23]["d20"].ToString());
        exSheet.Cells[29, 25].Value = double.Parse(dt.Rows[23]["d21"].ToString());
        exSheet.Cells[29, 26].Value = double.Parse(dt.Rows[23]["d22"].ToString());
        exSheet.Cells[29, 27].Value = double.Parse(dt.Rows[23]["d23"].ToString());
        exSheet.Cells[29, 28].Value = double.Parse(dt.Rows[23]["d24"].ToString());
        exSheet.Cells[29, 29].Value = double.Parse(dt.Rows[23]["d25"].ToString());
        exSheet.Cells[29, 30].Value = double.Parse(dt.Rows[23]["d26"].ToString());
        exSheet.Cells[29, 31].Value = double.Parse(dt.Rows[23]["d27"].ToString());
        exSheet.Cells[29, 32].Value = double.Parse(dt.Rows[23]["d28"].ToString());
        exSheet.Cells[29, 33].Value = double.Parse(dt.Rows[23]["d29"].ToString());
        exSheet.Cells[29, 34].Value = double.Parse(dt.Rows[23]["d30"].ToString());
        exSheet.Cells[29, 35].Value = double.Parse(dt.Rows[23]["d31"].ToString());

        exSheet.Cells[30, 3].Value = double.Parse(dt.Rows[24]["mm_sum"].ToString());
        exSheet.Cells[30, 4].Value = double.Parse(dt.Rows[24]["avg_month_amt"].ToString());
        exSheet.Cells[30, 5].Value = double.Parse(dt.Rows[24]["d1"].ToString());
        exSheet.Cells[30, 6].Value = double.Parse(dt.Rows[24]["d2"].ToString());
        exSheet.Cells[30, 7].Value = double.Parse(dt.Rows[24]["d3"].ToString());
        exSheet.Cells[30, 8].Value = double.Parse(dt.Rows[24]["d4"].ToString());
        exSheet.Cells[30, 9].Value = double.Parse(dt.Rows[24]["d5"].ToString());
        exSheet.Cells[30, 10].Value = double.Parse(dt.Rows[24]["d6"].ToString());
        exSheet.Cells[30, 11].Value = double.Parse(dt.Rows[24]["d7"].ToString());
        exSheet.Cells[30, 12].Value = double.Parse(dt.Rows[24]["d8"].ToString());
        exSheet.Cells[30, 13].Value = double.Parse(dt.Rows[24]["d9"].ToString());
        exSheet.Cells[30, 14].Value = double.Parse(dt.Rows[24]["d10"].ToString());
        exSheet.Cells[30, 15].Value = double.Parse(dt.Rows[24]["d11"].ToString());
        exSheet.Cells[30, 16].Value = double.Parse(dt.Rows[24]["d12"].ToString());
        exSheet.Cells[30, 17].Value = double.Parse(dt.Rows[24]["d13"].ToString());
        exSheet.Cells[30, 18].Value = double.Parse(dt.Rows[24]["d14"].ToString());
        exSheet.Cells[30, 19].Value = double.Parse(dt.Rows[24]["d15"].ToString());
        exSheet.Cells[30, 20].Value = double.Parse(dt.Rows[24]["d16"].ToString());
        exSheet.Cells[30, 21].Value = double.Parse(dt.Rows[24]["d17"].ToString());
        exSheet.Cells[30, 22].Value = double.Parse(dt.Rows[24]["d18"].ToString());
        exSheet.Cells[30, 23].Value = double.Parse(dt.Rows[24]["d19"].ToString());
        exSheet.Cells[30, 24].Value = double.Parse(dt.Rows[24]["d20"].ToString());
        exSheet.Cells[30, 25].Value = double.Parse(dt.Rows[24]["d21"].ToString());
        exSheet.Cells[30, 26].Value = double.Parse(dt.Rows[24]["d22"].ToString());
        exSheet.Cells[30, 27].Value = double.Parse(dt.Rows[24]["d23"].ToString());
        exSheet.Cells[30, 28].Value = double.Parse(dt.Rows[24]["d24"].ToString());
        exSheet.Cells[30, 29].Value = double.Parse(dt.Rows[24]["d25"].ToString());
        exSheet.Cells[30, 30].Value = double.Parse(dt.Rows[24]["d26"].ToString());
        exSheet.Cells[30, 31].Value = double.Parse(dt.Rows[24]["d27"].ToString());
        exSheet.Cells[30, 32].Value = double.Parse(dt.Rows[24]["d28"].ToString());
        exSheet.Cells[30, 33].Value = double.Parse(dt.Rows[24]["d29"].ToString());
        exSheet.Cells[30, 34].Value = double.Parse(dt.Rows[24]["d30"].ToString());
        exSheet.Cells[30, 35].Value = double.Parse(dt.Rows[24]["d31"].ToString());

        

        

        //----------------------
        ////end-set-----DataBind--in---Master---


        //set date title of year
        //exSheet.Cells[2, 1].Value = "Income Statement Year" + " " + l_year;

        //set data to detail.
        // loop detail not percent
        /*for (int l_row = 1; l_row <= dt.Rows.Count; l_row++)
        {
            for (int col = 4; col <= 34; col++)
            {


                if (double.Parse(dt.Rows[l_row - 1][col].ToString()) ==0.0)
                {
                    exSheet.Cells[5 + l_row, col + 1].Value ="";
                    
                }
                //exSheet.Cells[l_row + 12, 1].HorizontalAlignment = XlHAlign.xlHAlignCenter;
            }
        }*/
        // end loop detail percent
        if (File.Exists(TempFile))
        {
            File.Delete(TempFile);
        }


        // hide row firts 

        range = exSheet.Range["A1"];
        // hide row A5 
        range.Rows.Hidden = true;

        // font bold header

        exBook.SaveAs(TempFile);
        //ESysLib.ExcelToPdf(TempFile);
        //string pdfFilePath = TempFile.Replace(".xls", ".pdf");
        //write out to client broswer
        System.IO.FileInfo file = new System.IO.FileInfo(TempFile);
        //System.IO.FileInfo file = new System.IO.FileInfo(pdfFilePath);
        Response.Clear();
        Response.Charset = "UTF-8";
        Response.ContentEncoding = System.Text.Encoding.UTF8;
        //Add header, give a default file name for "File Download/Store as"
        Response.AddHeader("Content-Disposition", "attachment; filename=" + Server.UrlEncode(file.Name));
        //Add header, set file size to enable browser display download progress
        Response.AddHeader("Content-Length", file.Length.ToString());
        //Set the return string is unavailable reading for client, and must be downloaded
        Response.ContentType = "application/ms-exSheet";
        //Response.ContentType = "application/pdf";
        //Send file string to client 
        Response.WriteFile(TempFile);
        //Response.WriteFile(pdfFilePath);
        //Stop execute  
        Response.End();

    }
}