
<html xmlns:gw >
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
<meta http-equiv="Expires" content="Mon,06 Jan 1990 00:00:01 GMT"/>
  <LINK  href="/stdgw/system/default.css" rel="stylesheet" />
  <LINK  href="/stdgw/system/controls/css/button/style.css" rel="stylesheet" />

  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/vsflexgridconst.js"></script>
  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/default.js"></script>
  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/common.js"></script>
  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/template.js"></script>
  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/globalVar.js"></script>
  <script LANGUAGE="JavaScript" SRC="/stdgw/system/lib/ajax.js"></script>
</head>


<style>
  @media all
  {
  gw\:textbox  {  behavior: url(/stdgw/system/controls/textbox.htc) ;  }
  gw\:button  {  behavior: url(/stdgw/system/controls/button.htc) ;  }
  gw\:icon {  behavior: url(/stdgw/system/controls/icon.htc) ;  }
  gw\:label {  behavior: url(/stdgw/system/controls/label.htc) ;  }
  gw\:htmledit {  behavior: url(/stdgw/system/controls/htmledit.htc) ;  }
  gw\:treeview {  behavior: url(/stdgw/system/controls/treeview.htc) ;  }
  gw\:grid {  behavior: url(/stdgw/system/controls/grid.htc) ;  }
  gw\:datagrid {  behavior: url(/stdgw/system/controls/datagrid.htc) ;  }
  gw\:gridhtml {  behavior: url(/stdgw/system/controls/gridhtml.htc) ;  }
  gw\:textarea {  behavior: url(/stdgw/system/controls/textarea.htc) ;  }
  gw\:radio {  behavior: url(/stdgw/system/controls/radio.htc) ;  }
  gw\:checkbox {  behavior: url(/stdgw/system/controls/checkbox.htc) ;  }
  gw\:list {  behavior: url(/stdgw/system/controls/list.htc) ; }
  gw\:tab {  behavior: url(/stdgw/system/controls/tab.htc) ;  }
  gw\:datebox {  behavior: url(/stdgw/system/controls/datebox.htc) ;  }
  gw\:image{  behavior: url(/stdgw/system/controls/image.htc) ;  }
  gw\:data{  behavior: url(/stdgw/system/controls/data.htc) ;  }
  gw\:tree {  behavior: url(/stdgw/system/controls/tree.htc) ;  }
  gw\:download  {  behavior: url(/stdgw/system/controls/download.htc) ;  }
  gw\:imgBtn {  behavior: url(/stdgw/system/controls/imageBtn.htc) ;  }
  gw\:neogrid{  behavior: url(/stdgw/system/controls/neogrid.htc) ;  }
  gw\:label2 {  behavior: url(/stdgw/system/controls/label2.htc) ;  }
  }
  v\:* {behavior:url(#default#VML);}
  o\:* {behavior:url(#default#VML);}
  .shape {behavior:url(#default#VML);}
  .effect { behavior:  url(/stdgw/system/lib/effect.htc) }


</style>
  <script>
    function BodyInitInternal()
    {
            
         if ( typeof(BodyInit) != "undefined" )
             window.setTimeout("BodyInit()", 0);
    }

    function BodyCloseInternal()
    {
      if ( typeof(BodyClose) != "undefined" )
      BodyClose();
    }

    window.onload = BodyInitInternal;
    window.onunload = BodyCloseInternal;
  </script>

  