(function() {
(function (){ 
var d=Error,aa=encodeURIComponent,g=google_exportSymbol,h=String,i=window,m=document,n=google_exportProperty,o=Math;function ba(a,b){return a.toString=b}var p="setDate",r="appendChild",s="push",t="getMonth",u="length",v="prototype",ca="test",w="replace",da="getSeconds",x="floor",ea="constructor",y="getDate",z="indexOf",A="style",C="call",fa="draw",D="createElement",E="getFullYear",F="type",ga="getHours",ha="getMinutes",H="splice",ia="getTime",I="join",ja=ja||{};var J="object",K="number",ka="length",
la="array",ma="function",na="null",pa=function(a){var b=typeof a;if(b==J)if(a){if(typeof a[u]==K&&typeof a[H]!="undefined"&&!oa(a,ka))return la;if(typeof a[C]!="undefined")return ma}else return na;else if(b==ma&&typeof a[C]=="undefined")return J;return b};if(Object[v].propertyIsEnumerable)var oa=function(a,b){return Object[v].propertyIsEnumerable[C](a,b)};else oa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object[v].hasOwnProperty[C](a,b))return true;return false};var qa=function(a){var b=pa(a);
return b==J||b==la||b==ma},ra=Date.now||function(){return(new Date)[ia]()},sa=function(a,b){function c(){}c.prototype=b[v];a.db=b[v];a.prototype=new c;a[v].constructor=a};var ta=function(a){var b={};for(var c in a)b[c]=a[c];return b};var L=function(a){if(a){this.g=a.cols;this.e=a.rows}else{this.g=[];this.e=[]}},M="boolean",N="string",ua="date",va="timeofday",wa="datetime",xa={b:M,n:K,t:N,d:ua,m:va,s:wa},ya="sortColumns must be a non-empty array",za="column",Aa="sortColumns[",Ea='] must have a property "column"',Fa="desc",Ga='Property "desc" in sortColumns[',Ha="] must be boolean.",Ia="Column index ",Ja=" is duplicate in sortColumns.",Ka=function(a){if(typeof a!=J||a[ea]!=Array||a[u]<1)throw d(ya);var b={};for(var c=0;c<a[u];c++){if(typeof a[c]!=
J||!(za in a[c]))throw d(Aa+c+Ea);else if(Fa in a[c]&&typeof a[c].desc!=M)throw d(Ga+c+Ha);var e=a[c].column;if(e in b)throw d(Ia+e+Ja);b[e]=true}},La="columnFilters must be a non-empty array",Ma="value",Na="columnFilters[",Oa='] must have properties "column" and "value"',Pa=" is duplicate in columnFilters.",Qa=function(a){if(typeof a!=J||a[ea]!=Array||a[u]<1)throw d(La);var b={};for(var c=0;c<a[u];c++){if(typeof a[c]!=J||!(za in a[c])||!(Ma in a[c]))throw d(Na+c+Oa);var e=a[c].column;if(e in b)throw d(Ia+
e+Pa);b[e]=true}},O=function(a,b,c){if(b==null&&c==null)return 0;else if(b==null)return-1;else if(c==null)return 1;switch(a){case M:case K:case N:case ua:case wa:return b<c?-1:c<b?1:0;case va:for(var e=0;e<3;e++)if(b[e]<c[e])return-1;else if(c[e]<b[e])return 1;var f=b[u]<4?0:b[3],j=c[u]<4?0:c[3];return f<j?-1:j<f?1:0}};L[v].g=null;L[v].e=null;var Ra=function(){return this.e[u]};L[v].$=Ra;var Sa=function(){return this.g[u]};L[v].Z=Sa;var Ta=function(){var a=new L;a.g=[];a.e=[];for(var b=0;b<this.g[u];b++){var c=
this.g[b],e=ta(c),f=c.p;if(f)e.p=ta(f);a.g[s](e)}for(var j=0;j<this.e[u];j++){var l=this.e[j],k=[];for(var b=0;b<l[u];b++){var q=l[b],B=ta(q);if(q){var G=q.p;if(G)B.p=ta(G)}k[s](B)}a.e[s](k)}return a},Ua="Invalid row index ",Va=". Should be in the range [0-",Wa="].";L[v].k=function(a){if(typeof a!=K||a!=o[x](a)||a<0||a>=this.e[u])throw d(Ua+a+Va+(this.e[u]-1)+Wa);};var Xa="Invalid column index ";L[v].c=function(a){if(typeof a!=K||a!=o[x](a)||a<0||a>=this.g[u])throw d(Xa+a+Va+(this.g[u]-1)+Wa);};var Ya=
"Invalid type encountered at column index ",Za=": ",$a="Type mismatch. Value ",ab=" does not match type ",bb=" in column index ";L[v].M=function(a,b){if(b==null)return;var c=this.l(a),e=typeof b;switch(c){case K:if(e==K)return;break;case N:if(e==N)return;break;case M:if(e==M)return;break;case ua:case wa:if(e==J&&b[ea]==Date)return;break;case va:if(e==J&&b[ea]==Array&&b[u]>=3&&b[u]<=4){var f=true;for(var j=0;j<b[u];j++){var l=b[j];if(typeof l!=K||l!=o[x](l)){f=false;break}}if(b[0]<0||b[0]>23||b[1]<
0||b[1]>59||b[2]<0||b[2]>59)f=false;if(b[u]==4&&(b[4]<0||b[4]>999))f=false;if(f)return}break;default:throw d(Ya+a+Za+c);}throw d($a+b+ab+c+bb+a);};var cb=function(a){this.c(a);return this.g[a].id};L[v].Q=cb;var db=function(a){var b=this.g;for(var c=0;c<b[u];c++)if(b[c].id==a)return c;return-1};L[v].R=db;var eb=function(a){this.c(a);return this.g[a].label};L[v].S=eb;var fb=function(a){this.c(a);return this.g[a].pattern};L[v].T=fb;var gb=function(a){this.c(a);var b=this.g[a][F];return xa[b]};L[v].l=
gb;var hb=function(a,b){this.k(a);this.c(b);var c=this.e[a][b];return c?c.v:null};L[v].o=hb;var P="",ib="m",jb="0",kb=":",lb=function(a,b){this.k(a);this.c(b);var c=this.e[a][b],e=P;if(c)if(c.f!=null)e=c.f;else if(c.v!=null)if(this.g[b][F]==ib){var f=[],j=c.v;f[s](j[0]);var l=(j[1]<10?jb:P)+j[1];f[s](l);var k=(j[2]<10?jb:P)+j[2];f[s](k);e=f[I](kb)}else e=h(c.v);return e};L[v].Y=lb;var mb=function(a,b,c){this.k(a);this.c(b);var e=this.e[a][b],f=e&&e.p;return f&&c in f?f[c]:null};L[v].aa=mb;var nb=
function(a,b){this.k(a);this.c(b);var c=this.e[a][b];c||(c=this.e[a][b]={v:null});c.p||(c.p={});return c.p};L[v].Ea=nb;var rb=function(a,b,c){this.k(a);this.c(b);this.M(b,c);var e=this.e[a][b];e||(e=this.e[a][b]={});e.v=c},sb=function(a,b,c){this.k(a);this.c(b);var e=this.e[a][b];e||(e=this.e[a][b]={v:null});e.f=c},tb=function(a,b,c){this.k(a);this.c(b);var e=this.e[a][b];e.p=c};L[v].setProperty=function(a,b,c,e){var f=this.Ea(a,b);f[c]=e};var ub=function(a,b,c,e,f){this.k(a);this.c(b);this.M(b,c);
var j=this.e[a][b];j.v=c;j.f=typeof e!="undefined"?e:null;j.p=typeof f!="undefined"?f:null},vb=function(a,b){this.c(a);var c=this.g[a];c.label=b},wb=function(a,b){this.c(a);var c=this.g[a];c.p=b},xb=function(a,b,c){var e=this.na(a);e[b]=c},yb=function(a,b){var c=this.na(a);return c&&b in c?c[b]:null};L[v].U=yb;L[v].na=function(a){this.c(a);var b=this.g[a];b.p||(b.p={});return b.p};var zb="Invalid type: ",Ab=".",Bb=function(a,b,c,e){a!=this.g[u]&&this.c(a);var f=c||P,j=e||P,l=null;for(var k in xa)if(xa[k]==
b){l=k;break}if(l==null)throw d(zb+b+Ab);this.g[H](a,0,{id:j,label:f,pattern:P,type:l});for(var q=0;q<this.e[u];q++)this.e[q][H](a,0,{v:null,f:null})};L[v].Ha=Bb;var Cb=function(a,b,c){this.Ha(this.g[u],a,b,c);return this.g[u]-1},Db="Invalid value for numRows: ",Eb=". numRows should be a positive integer.",Fb=function(a,b){a!=this.e[u]&&this.k(a);if(typeof b!=K||b!=o[x](b)||b<0)throw d(Db+b+Eb);for(var c=0;c<b;c++){var e=[];for(var f=0;f<this.g[u];f++)e[s]({v:null,f:null});this.e[H](a,0,e)}return a+
b-1};L[v].Ia=Fb;var Gb=function(a){return this.Ia(this.e[u],a)};L[v].Ba=Gb;var Hb=function(){return this.Ba(1)},Ib=function(a){this.c(a);var b=this.l(a),c=null,e=null,f,j=this.e;for(f=0;f<j[u];f++){var l=j[f][a];if(l){var k=l.v;if(typeof k!="undefined"&&k!=null){c=k;e=k;break}}}if(c==null)return{min:null,max:null};for(f++;f<j[u];f++){var l=j[f][a];if(l){var k=l.v;if(typeof k!="undefined"&&k!=null)if(O(b,k,c)<0)c=k;else if(O(b,e,k)<0)e=k}}return{min:c,max:e}};L[v].V=Ib;L[v].ja=function(a){for(var b=
0;b<a[u];b++)this.c(a[b].column)};var Jb=function(a){Ka(a);this.ja(a);var b=[],c=this.e[u];for(var e=0;e<c;e++)b[s](e);var f=this;b.sort(function(j,l){for(var k=0;k<a[u];k++){var q=a[k].column,B=a[k].desc?-1:1,G=O(f.l(q),f.o(j,q),f.o(l,q));if(G!=0)return G*B}return 0});return b};L[v].H=Jb;L[v].sort=function(a){Ka(a);this.ja(a);var b=this;this.e.sort(function(c,e){for(var f=0;f<a[u];f++){var j=a[f].column,l=a[f].desc?-1:1,k=c[j]?c[j].v:null,q=e[j]?e[j].v:null,B=O(b.l(j),k,q);if(B!=0)return B*l}return 0})};
var Kb=function(a){this.c(a);var b=this.H([{column:a}]),c=this.l(a),e=[],f=this.o(b[0],a);e[s](f);for(var j=1;j<b[u];j++){var l=this.o(b[j],a);O(c,l,f)!=0&&e[s](l);f=l}return e};L[v].W=Kb;L[v].Ca=function(a){for(var b=0;b<a[u];b++){var c=a[b].column;this.c(c);this.M(c,a[b].value)}};L[v].Ka=function(a,b){for(var c=0;c<a[u];c++){var e=a[c],f=e.column;if(O(this.l(f),this.o(b,f),e.value)!=0)return false}return true};var Lb=function(a){Qa(a);this.Ca(a);var b=[],c=this.e[u];for(var e=0;e<c;e++)this.Ka(a,
e)&&b[s](e);return b};L[v].X=Lb;var Mb=function(a,b){if(b<=0)return;this.k(a);if(a+b>this.e[u])b=this.e[u]-a;this.e[H](a,b)};L[v].Na=Mb;var Nb=function(a){this.Na(a,1)},Ob=function(a,b){if(b<=0)return;this.c(a);if(a+b>this.g[u])b=this.g[u]-a;this.g[H](a,b);for(var c=0;c<this.e[u];c++)this.e[c][H](a,b)};L[v].Ma=Ob;var Pb=function(a){this.Ma(a,1)};var Qb="error",Q=function(a){this.A=a.status;this.G=a.reason||P;this.P=a.message||P;this.z=a.detailed_message||P;if(this.A!=Qb){this.xa=a.signature;this.h=new L(a.table)}};Q[v].A=P;Q[v].G=P;Q[v].P=P;Q[v].z=P;Q[v].xa=null;Q[v].h=null;var Rb=function(){return this.A==Qb};Q[v].Ja=Rb;var Sb="warning",Tb=function(){return this.A==Sb},Ub=function(){if(this.G)return[this.G];return[]};Q[v].D=function(a){return this.G==a};var Vb=function(){return this.h},Wb=function(){return this.P},Xb=function(){return this.z};var R=function(a){this.la=a;this.Va=/spreadsheets.google.com\/a\/.*\/tq\?.*pub\=1.*/[ca](a)||/.*corp.google.com:.*\/a\/.*\/tq\?.*pub\=1.*/[ca](a);this.Oa();this.Pa=Yb++;Zb[s](this)},$b,Yb=0,ac={};R[v].za=30;var Zb=[],bc=function(){for(var a=0;a<Zb[u];a++){var b=Zb[a];b.ha&&b.ia()}},cc="/tq?",dc="/tq?pub=1&";R[v].Oa=function(){var a=this.la;if(/.google\.com(\/a\/.*)?\/ccc\?.*key=/[ca](a))a=a[w](/\/ccc\?/,cc);else if(/.google\.com(\/a\/.*)?\/pub\?.*key=/[ca](a))a=a[w](/\/pub\?/,dc);this.la=a};var ec=
"#",fc="?",gc="&",hc="=",ic=function(a,b){var c=a[z](ec);if(c!=-1)a=a.substring(0,c);var e=a[z](fc),f=P,j=P,l=[];if(e==-1)f=a;else{f=a.substring(0,e);j=a.substring(e+1);l=j.split(gc)}var k,q=[];for(k=0;k<l[u];k++){var B=l[k].split(hc),G={};G.name=B[0];G.value=B[u]>1?B[1]:P;q[s](G)}for(var Ba in b){var ob=b[Ba],pb=false;for(k=0;k<q[u];k++)if(q[k].name==Ba){q[k].value=aa(ob);pb=true;break}if(!pb){var Ca={};Ca.name=Ba;Ca.value=aa(ob);q[s](Ca)}}var Da=f;if(q[u]>0){Da+=fc;var qb=[];for(k=0;k<q[u];k++)qb[s](q[k].name+
hc+q[k].value);Da+=qb[I](gc)}return Da},jc=function(a){var b=a.requestId,c=ac[b];if(c){ac[b]=null;c.B(a)}};R[v].va=null;R[v].I=null;R[v].K=null;R[v].u=null;R[v].ca=null;R[v].r=null;R[v].ha=true;R[v].ga=0;R[v].ra=null;R[v].fa=false;var kc="Refresh interval must be a non-negative number",lc=function(a){if(typeof a!=K||a<0)throw d(kc);this.ga=a;this.ua()};R[v].Ra=lc;R[v].N=function(){if(this.K){i.clearTimeout(this.K);this.K=null}};var mc="timeout",nc="Request timed out.";R[v].Sa=function(){var a={status:Qb,
reason:mc,message:nc};this.B(a)};var oc="reqId:",pc=";sig:",qc=";type:",rc=";";R[v].Aa=function(a){var b={};if(this.u)b.tq=h(this.u);var c=oc+h(this.Pa),e=this.ra;if(e)c+=pc+e;if(this.ca)c+=qc+this.ca;b.tqx=c;if(this.r){var f=[];for(var j in this.r)f[s](j+kb+this.r[j]);b.tqh=f[I](rc)}return ic(a,b)};var sc="body",tc="img",uc="none",vc="&requireauth=1&";R[v].ia=function(){var a=this.Aa(this.la);ac[h(this.Pa)]=this;var b=m.getElementsByTagName(sc)[0];if(this.Va){var c=this,e=m[D](tc);e.onerror=function(){c.L(a)};
e.onload=function(){c.L(a)};e[A].display=uc;var f=a+vc+(new Date)[ia]();e.src=f;b[r](e);return}this.L(a)};var wc="head",xc="script",yc="text/javascript";R[v].L=function(a){var b=this;this.N();this.K=i.setTimeout(function(){b.Sa()},this.za*1000);var c=m.getElementsByTagName(wc)[0],e=m[D](xc);e.type=yc;e.src=a;c[r](e);this.ua()};R[v].ya=function(){if(this.I){i.clearTimeout(this.I);this.I=null}};R[v].ua=function(){this.ya();if(this.ga!=0&&this.ha&&this.fa){var a=this;this.I=i.setTimeout(function(){a.ia()},
this.ga*1000)}};R[v].send=function(a){this.fa=true;this.va=a;this.ia()};R[v].abort=function(){this.fa=false;this.N();this.ya()};var zc="not_modified";R[v].B=function(a){this.N();var b=new Q(a);if(!b.D(zc)){this.ra=b.Ja()?null:b.xa;var c=this.va;c[C](c,b)}};var Ac="Timeout must be a positive number";R[v].setTimeout=function(a){if(typeof a!=K||isNaN(a)||a<=0)throw d(Ac);this.za=a};var Bc="Refreshable must be a boolean",Cc=function(a){if(typeof a!=M)throw d(Bc);return this.ha=a},Dc="queryString must be a string",
Ec=function(a){if(typeof a!=N)throw d(Dc);this.u=a},Fc=function(a){this.ca=a},Gc="\\\\",Hc="\\c",Ic="\\s",Jc=function(a,b){a=a[w](/\\/g,Gc);b=b[w](/\\/g,Gc);a=a[w](/:/g,Hc);b=b[w](/:/g,Hc);a=a[w](/;/g,Ic);b=b[w](/;/g,Ic);if(!this.r)this.r={};this.r[a]=b};function Kc(a,b){this.x=a;this.y=b}var Lc="(",Mc=", ",Nc=")";ba(Kc[v],function(){return Lc+this.x+Mc+this.y+Nc});var Oc="px";function Pc(a,b,c,e){this.width=a;this.height=b;this.fb=c||Oc;this.bb=e||Oc}ba(Pc[v],function(){return Lc+this.width+Mc+this.height+Nc});var Qc=["opera","msie","applewebkit","firefox","camino","mozilla"],Rc=["x11;","macintosh","windows"],Sc="[ /]?([0-9]+(.[0-9]+)?)",Tc="intel";function Uc(a){this.type=-1;this.os=-1;this.cpu=-1;this.version=0;this.revision=0;var a=a.toLowerCase();for(var b=0;b<Qc[u];b++){var c=Qc[b];if(a[z](c)!=-1){this.type=b;var e=new RegExp(c+Sc);if(e.exec(a))this.version=parseFloat(RegExp.$1);break}}for(var b=0;b<Rc[u];b++){var c=Rc[b];if(a[z](c)!=-1){this.os=b;break}}if(this.os==1&&a[z](Tc)!=-1)this.cpu=0;if(this.La()&&
/\brv:\s*(\d+\.\d+)/.exec(a))this.revision=parseFloat(RegExp.$1)}Uc[v].La=function(){return this[F]==3||this[F]==5||this[F]==4};var Vc=new Uc(navigator.userAgent);function Wc(a,b,c){var e=0;for(var f=0;f<a[u];++f)if(a[f]===b||c&&a[f]==b){a[H](f--,1);e++}return e}function Xc(a,b){var c=a[u];for(var e=0;e<c;++e)b(a[e],e)}function Yc(a,b,c){for(var e in a)if(c||!a.hasOwnProperty||a.hasOwnProperty(e))b(e,a[e])}function Zc(a,b,c,e){var f=$c(c,0),j=$c(e,b[u]);for(var l=f;l<j;++l)a[s](b[l])}function ad(){return Function[v][C].apply(Array[v].slice,arguments)}function $c(a,b){return typeof a!="undefined"&&a!=null?a:b}function S(a){if(!a.j)a.j=new a;return a.j};var bd="blur",cd="click",dd="dblclick",ed="focus",fd="unload",gd="focusin",hd="focusout";var id=false;function T(){this.q=[]}T[v].removeListener=function(a){var b=a.Ga;if(b<0)return;var c=this.q.pop();if(b<this.q[u]){this.q[b]=c;c.J(b)}a.J(-1)};T[v].ta=function(a){this.q[s](a);a.J(this.q[u]-1)};T[v].clear=function(){for(var a=0;a<this.q[u];++a)this.q[a].J(-1);this.q=[]};function jd(a,b,c){var e=S(U).C(a,b,c,0);S(T).ta(e);return e}function kd(a){a.remove();S(T).removeListener(a)}function ld(a,b){var c=[],e=a.__e_;if(e)if(b)e[b]&&Zc(c,e[b]);else Yc(e,function(f,j){Zc(c,j)});return c}function md(a,
b,c){var e=null,f=a.__e_;if(f){e=f[b];if(!e){e=[];if(c)f[b]=e}}else{e=[];if(c){a.__e_={};a.__e_[b]=e}}return e}function nd(a,b){var c=ad(arguments,2);Xc(ld(a,b),function(e){if(id)e.ea(c);else try{e.ea(c)}catch(f){}})}var od="on";function pd(a,b,c){var e;if(Vc[F]==2&&Vc.version<419.2&&b==dd){a[od+b]=c;e=S(U).C(a,b,c,3)}else if(a.addEventListener){var f=false;if(b==gd){b=ed;f=true}else if(b==hd){b=bd;f=true}var j=f?4:1;a.addEventListener(b,c,f);e=S(U).C(a,b,c,j)}else if(a.attachEvent){e=S(U).C(a,b,
c,2);a.attachEvent(od+b,e.Da())}else{a[od+b]=c;e=S(U).C(a,b,c,3)}if(a!=i||b!=fd)S(T).ta(e);return e}function U(){this.qa=null}U[v].Qa=function(a){this.qa=a};U[v].C=function(a,b,c,e){return this.qa?new this.qa(a,b,c,e):null};function qd(a,b,c,e){var f=this;f.j=a;f.F=b;f.da=c;f.pa=null;f.Wa=e;f.Ga=-1;md(a,b,true)[s](f)}var rd="A",sd="javascript:void(0)";qd[v].Da=function(){var a=this;return this.pa=function(b){if(!b)b=i.event;if(b&&!b.target)try{b.target=b.srcElement}catch(c){}var e=a.ea([b]);if(b&&
cd==b[F]){var f=b.srcElement;if(f&&rd==f.tagName&&sd==f.href)return false}return e}};qd[v].remove=function(){var a=this;if(!a.j)return;switch(a.Wa){case 1:a.j.removeEventListener(a.F,a.da,false);break;case 4:a.j.removeEventListener(a.F,a.da,true);break;case 2:a.j.detachEvent(od+a.F,a.pa);break;case 3:a.j[od+a.F]=null;break}Wc(md(a.j,a.F),a);a.j=null;a.da=null;a.pa=null};qd[v].J=function(a){this.Ga=a};qd[v].ea=function(a){if(this.j)return this.da.apply(this.j,a)};S(U).Qa(qd);var V=function(a,b,c){var e=typeof c!="undefined"?a.toFixed(c):h(a),f=e[z](Ab);if(f==-1)f=e[u];return(new Array(o.max(0,b-f)+1))[I](jb)+e};var td=function(a,b){switch(b){case 1:return a%4==0&&(a%100!=0||a%400==0)?29:28;case 5:case 8:case 10:case 3:return 30}return 31},ud="y",vd="d",wd="h",xd="n",yd="s",zd=function(a,b,c,e,f,j){if(typeof a==N){var l=a,k=b;this.years=l==ud?k:0;this.months=l==ib?k:0;this.days=l==vd?k:0;this.hours=l==wd?k:0;this.minutes=l==xd?k:0;this.seconds=l==yd?k:0}else{this.years=a||0;this.months=b||0;this.days=c||0;this.hours=e||0;this.minutes=f||0;this.seconds=j||0}},Ad="PT0S",Bd="-",Cd="P",Dd="Y",Ed="M",Fd="D",Gd=
"T",Hd="H",Id="S";zd[v].w=function(a){var b=o.min(this.years,this.months,this.days,this.hours,this.minutes,this.seconds),c=o.max(this.years,this.months,this.days,this.hours,this.minutes,this.seconds);if(b<0&&c>0)return null;if(!a&&b==0&&c==0)return Ad;var e=[];b<0&&e[s](Bd);e[s](Cd);if(this.years||a)e[s](o.abs(this.years)+Dd);if(this.months||a)e[s](o.abs(this.months)+Ed);if(this.days||a)e[s](o.abs(this.days)+Fd);if(this.hours||this.minutes||this.seconds||a){e[s](Gd);if(this.hours||a)e[s](o.abs(this.hours)+
Hd);if(this.minutes||a)e[s](o.abs(this.minutes)+Ed);if(this.seconds||a)e[s](o.abs(this.seconds)+Id)}return e[I](P)};zd[v].add=function(a){this.years+=a.years;this.months+=a.months;this.days+=a.days;this.hours+=a.hours;this.minutes+=a.minutes;this.seconds+=a.seconds};var W=function(a,b,c){if(!this.a)if(typeof a==K)this.a=new Date(a,b||0,c||1);else if(qa(a))this.a=new Date(a[E](),a[t](),a[y]());else{this.a=new Date(ra());this.a.setHours(0);this.a.setMinutes(0);this.a.setSeconds(0);this.a.setMilliseconds(0)}this.$a=
0;this.ab=3};W[v].getFullYear=function(){return this.a[E]()};W[v].oa=function(){return this[E]()};W[v].getMonth=function(){return this.a[t]()};W[v].getDate=function(){return this.a[y]()};W[v].getTime=function(){return this.a[ia]()};W[v].getDay=function(){return this.a.getDay()};W[v].getUTCFullYear=function(){return this.a.getUTCFullYear()};W[v].getUTCMonth=function(){return this.a.getUTCMonth()};W[v].getUTCDate=function(){return this.a.getUTCDate()};W[v].getUTCDay=function(){return this.a.getDay()};
W[v].getTimezoneOffset=function(){return this.a.getTimezoneOffset()};var Jd="Z",Kd="+";W[v].ba=function(){var a,b=this.a.getTimezoneOffset();if(b==0)a=Jd;else{var c=o.abs(b)/60,e=o[x](c),f=(c-e)*60;a=(b>0?Bd:Kd)+V(e,2)+kb+V(f,2)}return a};W[v].setFullYear=function(a){this.a.setFullYear(a)};W[v].wa=function(a){this.setFullYear(a)};W[v].setMonth=function(a){this.a.setMonth(a)};W[v].setDate=function(a){this.a[p](a)};W[v].setTime=function(a){this.a.setTime(a)};W[v].setUTCFullYear=function(a){this.a.setUTCFullYear(a)};
W[v].setUTCMonth=function(a){this.a.setUTCMonth(a)};W[v].setUTCDate=function(a){this.a.setUTCDate(a)};W[v].add=function(a){if(a.years||a.months){var b=this[t]()+a.months+a.years*12,c=this.oa()+o[x](b/12);b%=12;if(b<0)b+=12;var e=td(c,b),f=o.min(e,this[y]());this[p](1);this.wa(c);this.setMonth(b);this[p](f)}if(a.days)if(ja.userAgent&&!ja.userAgent.WEBKIT)this[p](this[y]()+a.days);else{var j=new Date(this.oa(),this[t](),this[y](),12),l=new Date(j[ia]()+a.days*86400000);this.wa(l[E]());this.setMonth(l[t]());
this[p](l[y]())}};W[v].w=function(a,b){var c=[this.a[E](),V(this.a[t]()+1,2),V(this.a[y](),2)];return c[I](a?Bd:P)+(b?this.ba():P)};ba(W[v],function(){return this.w()});var X=function(a,b,c,e,f,j,l){this.a=typeof a==K?new Date(a,b||0,c||1,e||0,f||0,j||0,l||0):new Date(a?a[ia]():ra());W[C](this)};sa(X,W);X[v].getHours=function(){return this.a[ga]()};X[v].getMinutes=function(){return this.a[ha]()};X[v].getSeconds=function(){return this.a[da]()};X[v].getMilliseconds=function(){return this.a.getMilliseconds()};
X[v].getUTCHours=function(){return this.a.getUTCHours()};X[v].getUTCMinutes=function(){return this.a.getUTCMinutes()};X[v].getUTCSeconds=function(){return this.a.getUTCSeconds()};X[v].getUTCMilliseconds=function(){return this.a.getUTCMilliseconds()};X[v].setHours=function(a){this.a.setHours(a)};X[v].setMinutes=function(a){this.a.setMinutes(a)};X[v].setSeconds=function(a){this.a.setSeconds(a)};X[v].setMilliseconds=function(a){this.a.setMilliseconds(a)};X[v].setUTCHours=function(a){this.a.setUTCHours(a)};
X[v].setUTCMinutes=function(a){this.a.setUTCMinutes(a)};X[v].setUTCSeconds=function(a){this.a.setUTCSeconds(a)};X[v].setUTCMilliseconds=function(a){this.a.setUTCMilliseconds(a)};X[v].add=function(a){W[v].add[C](this,a);a.hours&&this.setHours(this.a[ga]()+a.hours);a.minutes&&this.setMinutes(this.a[ha]()+a.minutes);a.seconds&&this.setSeconds(this.a[da]()+a.seconds)};var Ld=" ";X[v].w=function(a,b){if(a)return this.a[E]()+Bd+V(this.a[t]()+1,2)+Bd+V(this.a[y](),2)+Ld+V(this.a[ga](),2)+kb+V(this.a[ha](),
2)+kb+V(this.a[da](),2)+(b?this.ba():P);return this.a[E]()+V(this.a[t]()+1,2)+V(this.a[y](),2)+Gd+V(this.a[ga](),2)+V(this.a[ha](),2)+V(this.a[da](),2)+(b?this.ba():P)};ba(X[v],function(){return this.w()});var Md=function(a,b,c){if(a[z])return a[z](b,c);if(Array[z])return Array[z](a,b,c);var e=c==null?0:c<0?o.max(0,a[u]+c):c;for(var f=e;f<a[u];f++)if(f in a&&a[f]===b)return f;return-1};var Pd=function(a){return function(b){if(b.A==Qb){Nd(b,a);return false}else{Od(a);return true}}},Qd="span",Rd="background-color: #c00000; color: white;",Sd="user_not_authenticated",Td="invalid_query",Ud="br",Vd="background-color: white;",Nd=function(a,b){Od(b);var c=m[D](Qd);c[A].cssText=Rd;c[r](m.createTextNode(a.P));b[r](c);if(a.D(Sd)||a.D(Td)){b[r](m[D](Ud));var e=m[D](Qd);e[A].cssText=Vd;if(a.D(Sd))e.innerHTML=a.z;else e[r](m.createTextNode(a.z));b[r](e)}else b.title=a.z;b[A].display=P},Od=function(a){a.title=
P;while(a.childNodes[0])a.removeChild(a.childNodes[0]);a[A].display=uc};var Y={};Y.addListener=function(a,b,c){return jd(a,b,c)};Y.trigger=function(a,b,c){nd(a,b,c)};Y.addDomListener=function(a,b,c){return pd(a,b,c)};Y.removeListener=function(a){kd(a)};var Wd=function(a,b){this.cb=a;this.Xa=b},Xd=function(a,b,c,e){Wd[C](this,c,e);this.Za=a;this.eb=b};sa(Xd,Wd);var Yd="draw",Zd="Visualization must have a draw method.",Z=function(a,b,c,e){this.u=a;this.Ta=b;this.sa=c||{};this.Ua=e;this.O=null;if(e)this.O=Pd(e);if(!b||!(Yd in b)||typeof b[fa]!=ma)throw d(Zd);};Z[v].ka=null;Z[v].h=null;var $d=function(a){this.sa=a||{}};Z[v].draw=function(){if(!this.h)return;this.Ta[fa](this.h,this.sa)};var ae=function(a){var b=this.Ua;this.O=a?a:b?Pd(b):null},be="If no container was supplied, a custom error handler must be supplied instead.",ce=function(){if(!this.O)throw d(be);
var a=this.u,b=this;a.send(function(c){var e=b.ka;e&&e(c);b.B(c)})};Z[v].B=function(a){var b=this.O;if(b(a)){this.h=a.h;this.Ta[fa](this.h,this.sa)}};var de="Custom response handler must be a function.",ee=function(a){if(a==null){this.Ya=null;return}if(typeof a!=ma)throw d(de);this.ka=a};Z[v].abort=function(){this.u.abort()};var $=function(a){this.h=a;var b=[];for(var c=0;c<a.Z();c++)b[s](c);this.i=b};$[v].c=function(a){if(typeof a!=K||a!=o[x](a)||a<0||a>=this.i[u])throw d(Xa+a+Va+(this.i[u]-1)+Wa);};var fe=function(a){for(var b=0;b<a[u];b++)this.h.c(a[b]);this.i=a},ge=function(a){return Md(this.i,a)};$[v].Fa=ge;var he=function(a){this.c(a);return this.i[a]},ie=function(){return this.h.$()};$[v].$=ie;var je=function(){return this.i[u]};$[v].Z=je;var ke=function(a){this.c(a);return this.h.Q(this.i[a])};$[v].Q=ke;var le=
function(a){var b=this.h.R(a);return this.Fa(b)};$[v].R=le;var me=function(a){this.c(a);return this.h.S(this.i[a])};$[v].S=me;var ne=function(a){this.c(a);return this.h.T(this.i[a])};$[v].T=ne;var oe=function(a){this.c(a);return this.h.l(this.i[a])};$[v].l=oe;var pe=function(a,b){this.c(b);return this.h.o(a,this.i[b])};$[v].o=pe;var qe=function(a,b){this.c(b);return this.h.Y(a,this.i[b])};$[v].Y=qe;var re=function(a,b,c){this.c(b);return this.h.aa(a,this.i[b],c)};$[v].aa=re;var se=function(a,b){this.c(a);
return this.h.U(this.i[a],b)};$[v].U=se;var te=function(a){this.c(a);return this.h.V(this.i[a])};$[v].V=te;var ue=function(a){this.c(a);return this.h.W(this.i[a])};$[v].W=ue;var ve=function(a){Ka(a);for(var b=0;b<a[u];b++)a[b].column=this.i[a[b].column];return this.h.H(a)};$[v].H=ve;var we=function(a){Qa(a);for(var b=0;b<a[u];b++)a[b].column=this.i[a[b].column];return this.h.X(a)};$[v].X=we;var ye=function(){if(!xe){xe=true;i.IDIModule&&i.IDIModule.registerListener(bc,{pollingInterval:100})}},xe=false,ze="_table_query_url",Ae="http%",Be="https%",Ce="_table_query_refresh_interval",De=function(a){var b=a.getString(ze),c=b.toLowerCase();if(c[z](Ae)==0||c[z](Be)==0)b=decodeURIComponent(b);var e=new R(b),f=a.getInt(Ce);e.Ra(f);return e};ye[v].ma=null;var Ee="div",Fe="position: absolute; top:0; left: 0; display: none; padding: 2px; font-size: 0.8em",Ge=function(a){var b=this.ma;if(!b){b=this.ma=
m[D](Ee);b[A].cssText=Fe;m.body[r](b)}var c=Pd(b);return c(a)};var He="google.visualization.Query";g(He,R);var Ie="setRefreshInterval";n(R[v],Ie,lc);var Je="setQuery";n(R[v],Je,Ec);var Ke="send";n(R[v],Ke,R[v].send);var Le="setRefreshable";n(R[v],Le,Cc);var Me="setTimeout";n(R[v],Me,R[v].setTimeout);var Ne="setHandlerType";n(R[v],Ne,Fc);var Oe="setHandlerParameter";n(R[v],Oe,Jc);var Pe="setResponse";n(R,Pe,jc);var Qe="abort";n(R,Qe,$b);var Re="google.visualization.QueryResponse";g(Re,Q);var Se="getDataTable";n(Q[v],Se,Vb);var Te="isError";n(Q[v],Te,Rb);var Ue=
"hasWarning";n(Q[v],Ue,Tb);var Ve="getReasons";n(Q[v],Ve,Ub);var We="getMessage";n(Q[v],We,Wb);var Xe="getDetailedMessage";n(Q[v],Xe,Xb);var Ye="google.visualization.DataTable";g(Ye,L);var Ze="addColumn";n(L[v],Ze,Cb);var $e="addRow";n(L[v],$e,Hb);var af="addRows";n(L[v],af,Gb);var bf="clone";n(L[v],bf,Ta);var cf="getColumnId";n(L[v],cf,cb);var df="getColumnIndex";n(L[v],df,db);var ef="getColumnLabel";n(L[v],ef,eb);var ff="getColumnPattern";n(L[v],ff,fb);var gf="getColumnProperty";n(L[v],gf,yb);var hf=
"getColumnRange";n(L[v],hf,Ib);var jf="getColumnType";n(L[v],jf,gb);var kf="getDistinctValues";n(L[v],kf,Kb);var lf="getFilteredRows";n(L[v],lf,Lb);var mf="getFormattedValue";n(L[v],mf,lb);var nf="getNumberOfColumns";n(L[v],nf,Sa);var of="getNumberOfRows";n(L[v],of,Ra);var pf="getProperties";n(L[v],pf,nb);var qf="getProperty";n(L[v],qf,mb);var rf="getSortedRows";n(L[v],rf,Jb);var sf="getValue";n(L[v],sf,hb);var tf="insertColumn";n(L[v],tf,Bb);var uf="insertRows";n(L[v],uf,Fb);var vf="removeColumn";
n(L[v],vf,Pb);var wf="removeColumns";n(L[v],wf,Ob);var xf="removeRow";n(L[v],xf,Nb);var yf="removeRows";n(L[v],yf,Mb);var zf="setCell";n(L[v],zf,ub);var Af="setColumnLabel";n(L[v],Af,vb);var Bf="setColumnProperties";n(L[v],Bf,wb);var Cf="setColumnProperty";n(L[v],Cf,xb);var Df="setFormattedValue";n(L[v],Df,sb);var Ef="setProperties";n(L[v],Ef,tb);var Ff="setProperty";n(L[v],Ff,L[v].setProperty);var Gf="setValue";n(L[v],Gf,rb);var Hf="sort";n(L[v],Hf,L[v].sort);var If="google.visualization.DataView";
g(If,$);var Jf="setColumns";n($[v],Jf,fe);n($[v],cf,ke);n($[v],df,le);n($[v],ef,me);n($[v],ff,ne);n($[v],gf,se);n($[v],hf,te);n($[v],jf,oe);n($[v],kf,ue);var Kf="getTableColumnIndex";n($[v],Kf,he);n($[v],lf,we);n($[v],mf,qe);n($[v],nf,je);n($[v],of,ie);n($[v],qf,re);n($[v],rf,ve);n($[v],sf,pe);var Lf="getViewColumnIndex";n($[v],Lf,ge);var Mf="google.visualization.GadgetHelper";g(Mf,ye);var Nf="createQueryFromPrefs";n(ye[v],Nf,De);var Of="validateResponse";n(ye[v],Of,Ge);var Pf="google.visualization.events";
g(Pf,Y);var Qf="addListener";n(Y,Qf,Y.addListener);var Rf="trigger";n(Y,Rf,Y.trigger);var Sf="removeListener";n(Y,Sf,Y.removeListener);var Tf="google.visualization.QueryWrapper";g(Tf,Z);var Uf="setOptions";n(Z[v],Uf,$d);n(Z[v],Yd,Z[v][fa]);var Vf="setCustomErrorHandler";n(Z[v],Vf,ae);var Wf="sendAndDraw";n(Z[v],Wf,ce);var Xf="setResponseHandler";n(Z[v],Xf,ee);n(Z[v],Qe,Z[v].abort);
 })();

/**
 * SWFObject v1.4.2: Flash Player detection and embed - http://blog.deconcept.com/swfobject/
 *
 * SWFObject is (c) 2006 Geoff Stearns and is released under the MIT License:
 * http://www.opensource.org/licenses/mit-license.php
 *
 * **SWFObject is the SWF embed script formerly known as FlashObject. The name was changed for
 *   legal reasons.
 */
if(typeof deconcept=="undefined"){var deconcept=new Object();}
if(typeof deconcept.util=="undefined"){deconcept.util=new Object();}
if(typeof deconcept.SWFObjectUtil=="undefined"){deconcept.SWFObjectUtil=new Object();}
deconcept.SWFObject=function(_1,id,w,h,_5,c,_7,_8,_9,_a,_b){
if(!document.getElementById){return;}
this.DETECT_KEY=_b?_b:"detectflash";
this.skipDetect=deconcept.util.getRequestParameter(this.DETECT_KEY);
this.params=new Object();
this.variables=new Object();
this.attributes=new Array();
if(_1){this.setAttribute("swf",_1);}
if(id){this.setAttribute("id",id);}
if(w){this.setAttribute("width",w);}
if(h){this.setAttribute("height",h);}
if(_5){this.setAttribute("version",new deconcept.PlayerVersion(_5.toString().split(".")));}
this.installedVer=deconcept.SWFObjectUtil.getPlayerVersion();
if(c){this.addParam("bgcolor",c);}
var q=_8?_8:"high";
this.addParam("quality",q);
this.setAttribute("useExpressInstall",_7);
this.setAttribute("doExpressInstall",false);
var _d=(_9)?_9:window.location;
this.setAttribute("xiRedirectUrl",_d);
this.setAttribute("redirectUrl","");
if(_a){this.setAttribute("redirectUrl",_a);}};
deconcept.SWFObject.prototype={setAttribute:function(_e,_f){
this.attributes[_e]=_f;
},getAttribute:function(_10){
return this.attributes[_10];
},addParam:function(_11,_12){
this.params[_11]=_12;
},getParams:function(){
return this.params;
},addVariable:function(_13,_14){
this.variables[_13]=_14;
},getVariable:function(_15){
return this.variables[_15];
},getVariables:function(){
return this.variables;
},getVariablePairs:function(){
var _16=new Array();
var key;
var _18=this.getVariables();
for(key in _18){_16.push(key+"="+_18[key]);}
return _16;
},getSWFHTML:function(){
var _19="";
if(navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length){
if(this.getAttribute("doExpressInstall")){this.addVariable("MMplayerType","PlugIn");}
_19="<embed type=\"application/x-shockwave-flash\" src=\""+this.getAttribute("swf")+"\" width=\""+this.getAttribute("width")+"\" height=\""+this.getAttribute("height")+"\"";
_19+=" id=\""+this.getAttribute("id")+"\" name=\""+this.getAttribute("id")+"\" ";
var _1a=this.getParams();
for(var key in _1a){_19+=key+"=\""+_1a[key]+"\" ";}
var _1c=this.getVariablePairs().join("&");
if(_1c.length>0){_19+="flashvars=\""+_1c+"\"";}
_19+="/>";
}else{if(this.getAttribute("doExpressInstall")){
this.addVariable("MMplayerType","ActiveX");}
_19="<object id=\""+this.getAttribute("id")+"\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+this.getAttribute("width")+"\" height=\""+this.getAttribute("height")+"\">";
_19+="<param name=\"movie\" value=\""+this.getAttribute("swf")+"\" />";
var _1d=this.getParams();
for(var key in _1d){_19+="<param name=\""+key+"\" value=\""+_1d[key]+"\" />";}
var _1f=this.getVariablePairs().join("&");
if(_1f.length>0){_19+="<param name=\"flashvars\" value=\""+_1f+"\" />";}
_19+="</object>";}
return _19;
},write:function(_20){
if(this.getAttribute("useExpressInstall")){
var _21=new deconcept.PlayerVersion([6,0,65]);
if(this.installedVer.versionIsValid(_21)&&!this.installedVer.versionIsValid(this.getAttribute("version"))){
this.setAttribute("doExpressInstall",true);
this.addVariable("MMredirectURL",escape(this.getAttribute("xiRedirectUrl")));
document.title=document.title.slice(0,47)+" - Flash Player Installation";
this.addVariable("MMdoctitle",document.title);}}
if(this.skipDetect||this.getAttribute("doExpressInstall")||this.installedVer.versionIsValid(this.getAttribute("version"))){
var n=(typeof _20=="string")?document.getElementById(_20):_20;
n.innerHTML=this.getSWFHTML();
return true;
}else{
if(this.getAttribute("redirectUrl")!=""){document.location.replace(this.getAttribute("redirectUrl"));}}
return false;}};
deconcept.SWFObjectUtil.getPlayerVersion=function(){
var _23=new deconcept.PlayerVersion([0,0,0]);
if(navigator.plugins&&navigator.mimeTypes.length){
var x=navigator.plugins["Shockwave Flash"];
if(x&&x.description){_23=new deconcept.PlayerVersion(x.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s+r|\s+b[0-9]+)/,".").split("."));}
}else{
try{var axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");}
catch(e){try{
var axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
_23=new deconcept.PlayerVersion([6,0,21]);
axo.AllowScriptAccess="always";}
catch(e){
if(_23.major==6){return _23;}}try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");}
catch(e){}}
if(axo!=null){_23=new deconcept.PlayerVersion(axo.GetVariable("$version").split(" ")[1].split(","));}}
return _23;};
deconcept.PlayerVersion=function(_27){
this.major=_27[0]!=null?parseInt(_27[0],10):0;
this.minor=_27[1]!=null?parseInt(_27[1],10):0;
this.rev=_27[2]!=null?parseInt(_27[2],10):0;
};
deconcept.PlayerVersion.prototype.versionIsValid=function(fv){
if(this.major<fv.major){return false;}
if(this.major>fv.major){return true;}
if(this.minor<fv.minor){return false;}
if(this.minor>fv.minor){return true;}
if(this.rev<fv.rev){return false;}
return true;
};
deconcept.util={getRequestParameter:function(_29){
var q=document.location.search||document.location.hash;
if(q){
var _2b=q.substring(1).split("&");
for(var i=0;i<_2b.length;i++){
if(_2b[i].substring(0,_2b[i].indexOf("="))==_29){
return _2b[i].substring((_2b[i].indexOf("=")+1));}}}
return "";}};
deconcept.SWFObjectUtil.cleanupSWFs=function(){
var _2d=document.getElementsByTagName("OBJECT");
for(var i=0;i<_2d.length;i++){
_2d[i].style.display="none";
for(var x in _2d[i]){if(typeof _2d[i][x]=="function"){_2d[i][x]=null;}}}};
if(typeof window.onunload=="function"){
var oldunload=window.onunload;
window.onunload=function(){
deconcept.SWFObjectUtil.cleanupSWFs();
oldunload();};
}else{window.onunload=deconcept.SWFObjectUtil.cleanupSWFs;}
if(Array.prototype.push==null){
Array.prototype.push=function(_30){
this[this.length]=_30;
return this.length;};}

var getQueryParamValue=deconcept.util.getRequestParameter;
var FlashObject=deconcept.SWFObject; // for legacy support
var SWFObject=deconcept.SWFObject;
(function (){ 
function aa(a,b){return a.currentTarget=b}function ba(a,b){return a.keyCode=b}function d(a,b){return a.type=b}var j=false,n=null,o=true,q=Error,r=google_exportSymbol,s=String,t=document,u=google,v=Array,w="appendChild",x="push",y="length",A="prototype",B="getNumberOfColumns",ca="visualization",C="indexOf",D="style",F="call",da="createElement",ea="keyCode",G="getColumnType",fa="handleEvent",H="type",ga="apply",ha="getValue",ia=ia||{},I=this,ja=".",ka=function(a,b){var c=a.split(ja),e=b||I;for(var f;f=
c.shift();)if(e[f])e=e[f];else return n;return e};var la="object",J="number",ma="length",na="array",K="function",oa="null",qa=function(a){var b=typeof a;if(b==la)if(a){if(typeof a[y]==J&&typeof a.splice!="undefined"&&!pa(a,ma))return na;if(typeof a[F]!="undefined")return K}else return oa;else if(b==K&&typeof a[F]=="undefined")return la;return b};if(Object[A].propertyIsEnumerable)var pa=function(a,b){return Object[A].propertyIsEnumerable[F](a,b)};else pa=function(a,b){if(b in a)for(var c in a)if(c==
b&&Object[A].hasOwnProperty[F](a,b))return o;return j};var ra="closure_hashCode_",ta=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ra)){var b=a.B;if(b)return b}a.B||(a.B=++sa);return a.B},sa=0,ua=function(a,b){var c=a.Z;if(arguments[y]>2){var e=v[A].slice[F](arguments,2);c&&e.unshift[ga](e,c);c=e}b=a.aa||b;a=a.$||a;var f,g=b||I;f=c?function(){var i=v[A].slice[F](arguments);i.unshift[ga](i,c);return a[ga](g,i)}:function(){return a[ga](g,arguments)};f.Z=c;f.aa=b;f.$=a;return f},va=Date.now||function(){return(new Date).getTime()},
wa=function(a,b){function c(){}c.prototype=b[A];a.X=b[A];a.prototype=new c;a[A].constructor=a};var L=function(){};L[A].F=j;L[A].m=function(){if(!this.F){this.a();this.F=o}};L[A].a=function(){};var M=function(a,b){L[F](this);this.T=b;this.e=[];this.Q(a)};wa(M,L);M[A].q=n;M[A].r=n;M[A].l=function(a){this.q=a};M[A].N=function(a){this.r=a};M[A].c=function(){if(this.e[y])return this.e.pop();return this.C()};M[A].g=function(a){this.e[y]<this.T?this.e[x](a):this.D(a)};M[A].Q=function(a){if(a>this.T)throw q("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.e[x](this.C())};M[A].C=function(){return this.q?this.q():{}};M[A].D=function(a){if(this.r)this.r(a);
else if(qa(a.m)==K)a.m();else for(var b in a)delete a[b]};M[A].a=function(){M.X.a[F](this);var a=this.e;while(a[y])this.D(a.pop());delete this.e};va();var xa,ya,za,Aa,Ba,Ca,Da,Ga,Ha,Ia,Ja,N="",Ka="Opera",La="MSIE",Ma="WebKit",Na="Mobile",Oa="Gecko",Pa="Camino",Qa="Mac",Ra="Win",Sa="Linux",Ta=function(){var a=j,b=j,c=j,e=j,f=j,g=j,i=j,h=j,k=j,l=N;if(I.navigator){var m=I.navigator,p=m.userAgent;a=p[C](Ka)==0;b=!a&&p[C](La)!=-1;c=!a&&p[C](Ma)!=-1;k=c&&p[C](Na)!=-1;e=!a&&!c&&m.product==Oa;f=e&&m.vendor==Pa;var z,E;if(a)z=I.opera.version();else{if(e)E=/rv\:([^\);]+)(\)|;)/;else if(b)E=/MSIE\s+([^\);]+)(\)|;)/;else if(c)E=/WebKit\/(\S+)/;if(E){E.test(p);
z=RegExp.$1}}l=m.platform||N;g=l[C](Qa)!=-1;i=l[C](Ra)!=-1;h=l[C](Sa)!=-1}xa=a;ya=b;za=e;Aa=f;Ba=c;Ca=k;Da=z;Ga=l;Ha=g;Ia=i;Ja=h};Ta();var Ua=ya;var Va=function(a,b,c){if(a[C])return a[C](b,c);if(v[C])return v[C](a,b,c);var e=c==n?0:c<0?Math.max(0,a[y]+c):c;for(var f=e;f<a[y];f++)if(f in a&&a[f]===b)return f;return-1},Wa=function(a,b){var c=Va(a,b),e;if(e=c!=-1)v[A].splice[F](a,c,1)[y]==1;return e};var O=function(a,b){d(this,a);this.target=b;aa(this,this.target)};wa(O,L);O[A].a=function(){delete this[H];delete this.target;delete this.currentTarget};O[A].k=j;O[A].w=o;O[A].stopPropagation=function(){this.k=o};O[A].preventDefault=function(){this.w=j};var P=function(a,b){a&&this.i(a,b)};wa(P,O);d(P[A],n);P[A].target=n;P[A].relatedTarget=n;P[A].offsetX=0;P[A].offsetY=0;P[A].clientX=0;P[A].clientY=0;P[A].screenX=0;P[A].screenY=0;P[A].button=0;ba(P[A],0);P[A].charCode=0;P[A].ctrlKey=j;P[A].altKey=j;P[A].shiftKey=j;P[A].metaKey=j;P[A].b=n;var Xa="mouseover",Ya="mouseout",Za="keypress";P[A].i=function(a,b){d(this,a[H]);this.target=a.target||a.srcElement;aa(this,b);this.relatedTarget=a.relatedTarget?a.relatedTarget:this[H]==Xa?a.fromElement:this[H]==
Ya?a.toElement:n;this.offsetX=typeof a.layerX==J?a.layerX:a.offsetX;this.offsetY=typeof a.layerY==J?a.layerY:a.offsetY;this.clientX=typeof a.clientX==J?a.clientX:a.pageX;this.clientY=typeof a.clientY==J?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;ba(this,a[ea]||0);this.charCode=a.charCode||(this[H]==Za?a[ea]:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.b=a;delete this.w;delete this.k};P[A].stopPropagation=
function(){this.k=o;if(this.b.stopPropagation)this.b.stopPropagation();else this.b.cancelBubble=o};P[A].preventDefault=function(){this.w=j;if(this.b.preventDefault)this.b.preventDefault();else{this.b.returnValue=j;try{ba(this.b,-1)}catch(a){}}};P[A].a=function(){P.X.a[F](this);this.b=n};var Q=function(){},$a=0;Q[A].u=n;Q[A].j=n;Q[A].M=n;Q[A].src=n;d(Q[A],n);Q[A].A=n;Q[A].t=n;Q[A].f=0;Q[A].h=j;Q[A].z=j;Q[A].i=function(a,b,c,e,f,g){if(qa(a)==K)this.u=o;else if(a&&a[fa]&&qa(a[fa])==K)this.u=j;else throw q("Invalid listener argument");this.j=a;this.M=b;this.src=c;d(this,e);this.A=!!f;this.t=g;this.z=j;this.f=++$a;this.h=j};Q[A].handleEvent=function(a){if(this.u)return this.j[F](this.t||this.src,a);return this.j[fa][F](this.j,a)};var R={},S={},T={},U=new M(0,600);U.l(function(){return{d:0}});U.N(function(a){a.d=0});var V=new M(0,600);V.l(function(){return[]});V.N(function(a){a.length=0;delete a.n;delete a.L});var ab=new M(0,600);ab.l(function(){var a=function(b){return bb[F](a.src,a.f,b)};return a});var cb=function(){return new Q},db=new M(0,600);db.l(cb);var eb=function(){return new P},fb=function(){var a=n;if(Ua){a=new M(0,600);a.l(eb)}return a},gb=fb(),hb="on",ib={},jb=function(a,b,c,e,f){if(b)if(qa(b)==na){for(var g=0;g<
b[y];g++)jb(a,b[g],c,e,f);return n}else{var i=!!e,h=S;b in h||(h[b]=U.c());h=h[b];if(!(i in h)){h[i]=U.c();h.d++}h=h[i];var k=ta(a),l,m;if(h[k]){l=h[k];for(var g=0;g<l[y];g++){m=l[g];if(m.j==c&&m.t==f){if(m.h)break;return l[g].f}}}else{l=h[k]=V.c();h.d++}var p=ab.c();p.src=a;m=db.c();m.i(c,p,a,b,i,f);var z=m.f;p.f=z;l[x](m);R[z]=m;T[k]||(T[k]=V.c());T[k][x](m);if(a.addEventListener){if(a==I||!a.ba)a.addEventListener(b,p,i)}else a.attachEvent(kb(b),p);return z}else throw q("Invalid event type");},
mb=function(a){if(!R[a])return j;var b=R[a];if(b.h)return j;var c=b.src,e=b[H],f=b.M,g=b.A;if(c.removeEventListener){if(c==I||!c.ba)c.removeEventListener(e,f,g)}else c.detachEvent&&c.detachEvent(kb(e),f);var i=ta(c),h=S[e][g][i];if(T[i]){var k=T[i];Wa(k,b);k[y]==0&&delete T[i]}b.h=o;h.L=o;lb(e,g,i,h);delete R[a];return o},lb=function(a,b,c,e){if(!e.n)if(e.L){for(var f=0,g=0;f<e[y];f++){if(e[f].h){db.g(e[f]);continue}if(f!=g)e[g]=e[f];g++}e.length=g;e.L=j;if(g==0){V.g(e);delete S[a][b][c];S[a][b].d--;
if(S[a][b].d==0){U.g(S[a][b]);delete S[a][b];S[a].d--}if(S[a].d==0){U.g(S[a]);delete S[a]}}}},kb=function(a){if(a in ib)return ib[a];return ib[a]=hb+a},ob=function(a,b,c,e){var f=1,g=S;if(b in g){g=g[b];if(c in g){g=g[c];var i=ta(a);if(g[i]){var h=g[i];if(h.n)h.n++;else h.n=1;try{var k=h[y];for(var l=0;l<k;l++){var m=h[l];if(m&&!m.h)f&=nb(m,e)!==j}}finally{h.n--;lb(b,c,i,h)}}}}return Boolean(f)},nb=function(a,b){var c=a[fa](b);a.z&&mb(a.f);return c},pb="window.event",bb=function(a,b){if(!R[a])return o;
var c=R[a],e=c[H],f=S;if(!(e in f))return o;f=f[e];var g;if(Ua){var i=b||ka(pb),h=o in f;if(h){if(i[ea]<0||i.returnValue!=undefined)return o;qb(i)}ta(c.src);var k=gb.c();k.i(i,this);g=o;try{if(h){var l=V.c();for(var m=k.currentTarget;m;m=m.parentNode)l[x](m);for(var p=l[y]-1;!k.k&&p>=0;p--){aa(k,l[p]);g&=ob(l[p],e,o,k)}for(var p=0;!k.k&&p<l[y];p++){aa(k,l[p]);g&=ob(l[p],e,j,k)}}else g=nb(c,k)}finally{if(l){l.length=0;V.g(l)}k.m();gb.g(k)}return g}var z=new P(b,this);try{g=nb(c,z)}finally{z.m()}return g},
qb=function(a){var b=j;if(a[ea]==0)try{ba(a,-1);return}catch(c){b=o}if(b||a.returnValue==undefined)a.returnValue=o};var rb="http://www.google.com/uds",sb="1.0",tb="/modules/gviz/",ub=function(){var a=rb,b=sb;if(u&&u.loader&&u.loader.ServiceBase)a=u.loader.ServiceBase;if(u&&u[ca]&&u[ca].Version)b=u[ca].Version;return a+tb+b};var vb="div",wb="position: absolute; top: 0; left: 0;display: none;",xb="relative",W=function(a){if(!a)throw q("container passed to ErrorMessages is not defined.");this.p=a;this.G=t[da](vb);var b=this.G;b[D].cssText=wb;a[D].position=a[D].position||xb},yb="span",zb="font: 12px arial,sans-serif; background-color: #fff4c2; border: 1px solid black; padding: 3px; margin-bottom: 1px; white-space: nowrap; display: block;",Ab="font: normal 1.1em arial,sans-serif; font-weight: bold; color: #0000cc; cursor: pointer; padding: 3px 3px 3px 15px; color: black;",
Bb="mousedown",Cb="\u00d7";W[A].P=function(a,b){var c=t[da](yb);c[D].cssText=zb;c[w](t.createTextNode(a));if(b){var e=t[da](yb);e[D].cssText=Ab;jb(e,Bb,ua(this.R,this,c));e[w](t.createTextNode(Cb));c[w](e)}this.O(c)};var Db="block";W[A].O=function(a){var b=this.G;b[D].display=Db;b.parentNode!=this.p&&this.p[w](b);b[w](a)};var Eb="none";W[A].V=function(){var a=this.G;a[D].display=Eb;while(a.childNodes[0])a.removeChild(a.childNodes[0])};W[A].R=function(a){var b=a.parentNode;b.removeChild(a);if(b.childNodes[y]==
0)b[D].display=Eb};var Y=function(a){this.p=a;this.ca=new W(a);if(X)throw q("Only one instance of MotionChart can be used.");else X=this},X=n,Fb=ub()+"/motionchart/tlz-gviz.swf",Gb=0;Y[A].J=n;Y[A].s=n;Y[A].K=n;Y[A].o=n;Y[A].H=o;Y[A].v=N;var Hb="continuous",Ib="discrete",Jb="tlzswf",Lb=function(a,b){b=b||{};var c=this.p;if(!c)throw q("Container is not defined");if(!a)throw q("Data table is not defined");var e=this.ca;e.V();try{this.Y(a)}catch(f){e.P(f.message);return}var g=this.K=[],i=this.s={},h=this.o=[];this.J=a.getColumnLabel(0);
for(var k=2;k<a[B]();k++)g[x]({id:k-2,name:a.getColumnLabel(k),type:a[G](k)==J?Hb:Ib,hasTime:o});for(var l=2;l<a[B]();l++)h[l-2]=[];for(var m=0;m<a.getNumberOfRows();m++){var p=a[ha](m,0);i[p]=1;var z=Kb(a[ha](m,1),a[G](1));for(var E=2;E<a[B]();E++)this.U(a,E,p,z,m)}if(this.H){this.H=j;this.W(c,b);this.v=this.I(a)}else{var Ea=t.getElementById(Jb),Fa=this.I(a);if(Fa==this.v)Ea.dataChanged();else{Ea.metricTablesChanged();this.v=Fa}}},Z="string";Y[A].U=function(a,b,c,e,f){if(a[B]()>b){var g=a[ha](f,
b);g!=n&&!(a[G](b)==Z&&g==N)&&this.o[b-2][x]([c,e,g])}};var Mb=":",Nb=",";Y[A].I=function(a){var b=N;for(var c=0;c<a[B]();c++)b+=a[G](c)+Mb+a.getColumnLabel(c)+Nb;for(var e in this.s)b+=e;return b};Y[A].Y=function(a){if(a[B]()<3)throw q("There should be at least three columns in the data.");if(!(a[G](0)==Z&&this.S(a,1)))throw q("First and second columns must be entity and time.");var b=0,c=0;for(var e=2;e<a[B]();e++){if(a[G](e)!=J&&a[G](e)!=Z)throw q("All data columns must be string or numbers.");
if(a[G](e)==J)b++;else c++}if(b<1)throw q("There must be at least one numeric column.");};var Ob="date",Pb="datetime";Y[A].S=function(a,b){var c=a[G](b);switch(c){case J:return o;case Z:var e=a[ha](1,b);return/[0-9]{4}Q[1-4]/.test(e)||/[0-9]{4}W[0-9]{2}/.test(e);case Ob:return o;case Pb:return o;default:return j}};var Qb="9",Rb="#FFFFFF",Sb="scale",Tb="default",Ub="allowScriptAccess",Vb="always",Wb="state",Xb="wmode",Yb="opaque",Zb="google.visualiation.MotionChart-";Y[A].W=function(a,b){var c=Fb,
e=b.width||500,f=b.height||300,g=b.state||N,i=new SWFObject(c,Jb,e,f,Qb,Rb);i.addParam(Sb,Tb);i.addParam(Ub,Vb);i.addVariable(Wb,g);i.addParam(Xb,Yb);var h=t[da](vb);h.id=Zb+Gb++;a[w](h);i.write(h.id)};var $b="Q",ac="W",bc="0",cc="-",Kb=function(a,b){var c;if(b==J)c=s(a);else if(b==Z&&(a[C]($b)>-1||a[C](ac)>-1))c=s(a);else{c=s(a.getFullYear());var e=s(a.getMonth()+1);if(e[y]==1)e=bc+e;c+=cc+e;var f=s(a.getDate());if(f[y]==1)f=bc+f;c+=cc+f}return c},$="No instance of class motion chart.",dc=function(){if(X)return X.J;
else throw q($);},ec=function(){if(!X)throw q($);var a=[],b=X.s;for(var c in b)a[x](c);return a},fc=function(){if(X)return X.K;else throw q($);},gc=function(a){if(X)return X.o[a];else throw q($);},hc="statechange",ic=function(a){var b=X;if(b)u[ca].events.trigger(b,hc,{state:a});else throw q($);},jc=function(a){Fb=a};r("google.visualization.MotionChart",Y);google_exportProperty(Y[A],"draw",Lb);r("getIconLabel",dc);r("getMetricTables",fc);r("getIconDimensionValues",ec);r("getMetricTableData",gc);r("setTlzState",ic);r("setSwfUrl",jc);
 })();
google.loader.loaded({"module":"visualization","version":"1.0","components":["motionchart","default"]});
google.loader.eval.visualization = function() {eval(arguments[0])}})()